/** Auto-generated by scripts/write-build-meta.mjs — do not edit by hand. */
export const EMBEDDED_BUILD_META = {
  commit: "1e839c1505adf4d615f298bfd9ee3cf47bbb4d94" as string | null,
  shortCommit: "1e839c1505ad" as string | null,
  builtAt: "2026-08-11T09:50:30.743Z" as string | null,
  source: "git-rev-parse" as string,
} as const;
