/** Auto-generated by scripts/write-build-meta.mjs — do not edit by hand. */
export const EMBEDDED_BUILD_META = {
  commit: null as string | null,
  shortCommit: null as string | null,
  builtAt: null as string | null,
  source: "placeholder" as string,
} as const;
