/** Auto-generated by scripts/write-build-meta.mjs — do not edit by hand. */
export const EMBEDDED_BUILD_META = {
  commit: "64eadd4f988517396e2f9e3e3dad1288e39dc674" as string | null,
  shortCommit: "64eadd4f9885" as string | null,
  builtAt: "2026-08-10T22:38:48.738Z" as string | null,
  source: "git-rev-parse" as string,
} as const;
