/**
 * Phase 4 — SKU-keyed creative overrides for every active catalog template.
 * Pilots live here too so registry build stays single-source.
 * Layout DNA remains fallback; these overrides win for new defaults only.
 *
 * Typed loosely here to avoid circular imports with template-creative-registry.
 */
export type SkuCreativeOverride = Record<string, unknown>;

/** Explicit creative universes for every catalog SKU (Phase 3 pilots + Phase 4 remaining). */
export const SKU_CREATIVE_OVERRIDES: Record<string, SkuCreativeOverride> = {
  // ─── Phase 3 pilots (do not regress) ───────────────────────────────────────
  "royal-emerald-wedding": {
    creativeUniverse: "royal-wax-seal",
    creativeConcept: "Royal Wax Seal — gold-light intro into embossed emerald envelope; press the wax seal",
    emotionalTone: "regal",
    targetAudience: "Luxury weddings and formal ceremonies",
    visualLanguage: "deep emerald velvet, gold crown motifs, palace columns, embossed seal, paper and metal depth",
    openingSequence: "celeventic gold-foil shimmer → embossed emerald envelope → press wax seal",
    revealMechanic: "wax-seal-press",
    sceneArchitecture:
      "Gold light → Embossed envelope → Wax seal press → Couple → Ceremony timeline → Royal portrait gallery → RSVP → Seal-reform outro",
    motionProfile: "regal",
    parallaxProfile: "cinematic",
    typographySystem: "luxury-serif",
    buttonFamily: "embossed-royal",
    backgroundSystem: "velvet-marble",
    mediaPresentationStyle: "luxury-frame",
    compatibleAudioCategories: ["orchestra", "strings", "harp", "cinematic", "wedding"],
    prohibitedAudioCategories: ["edm", "party", "neon", "drums-loud", "funeral", "memorial"],
    soundEffectProfile: "seal-press",
    outroType: "seal-reform",
    introVariant: "gold-foil",
    openingExperience: "wax-seal-emerald",
    sceneTransition: "curtain",
    outroExperience: "seal-reform",
    slideshowStyle: "luxury-frame",
    countdownStyle: "gold-royal",
    packageAccess: "premium",
    reducedMotionFallback: "static palace card with Skip to details",
    primaryActions: ["RSVP", "SEATING", "GALLERY", "LOCATION", "SAVE_DATE", "SHARE"],
    audioDirectorProfile: "royal-orchestra",
  },
  "floral-garden-romance": {
    creativeUniverse: "botanical-romance",
    creativeConcept: "Botanical Bloom — living romantic garden; logo bloom into petal reveal and floating frames",
    emotionalTone: "romantic",
    targetAudience: "Engagements and garden weddings",
    visualLanguage: "soft petals, rose light, floating botanical frames, leaf depth layers, flower parallax",
    openingSequence: "celeventic floral logo bloom → tap flower / swipe petals",
    revealMechanic: "flower-bloom-swipe",
    sceneArchitecture:
      "Logo bloom → Flower petal reveal → Couple → Story path → Floating botanical frames → Ceremony garden → Countdown → RSVP → Petals thank-you",
    motionProfile: "organic",
    parallaxProfile: "interactive",
    typographySystem: "romantic-script",
    buttonFamily: "floral-edge",
    backgroundSystem: "floating-flowers",
    mediaPresentationStyle: "floating-memories",
    compatibleAudioCategories: ["acoustic", "piano", "garden", "strings-soft", "wedding"],
    prohibitedAudioCategories: ["edm", "corporate", "neon", "funeral", "memorial"],
    soundEffectProfile: "petal-soft",
    outroType: "rose-petals",
    introVariant: "logo-bloom",
    openingExperience: "flower-bloom",
    sceneTransition: "sparkle",
    outroExperience: "rose-petals",
    slideshowStyle: "floating-memories",
    countdownStyle: "ring",
    packageAccess: "free",
    reducedMotionFallback: "static garden cover with Continue",
    primaryActions: ["RSVP", "COUNTDOWN", "GALLERY", "SHARE", "LOCATION", "SAVE_DATE"],
    audioDirectorProfile: "garden-piano",
  },
  "midnight-velvet-reception": {
    creativeUniverse: "editorial-love-story",
    creativeConcept: "Editorial Love Story — title card into magazine cover; swipe page-turn chapters",
    emotionalTone: "editorial",
    targetAudience: "Reception soirées and fashion-forward couples",
    visualLanguage: "asymmetric crops, silver type, velvet darkness, film-strip collage, credit typography",
    openingSequence: "celeventic film title → magazine cover → swipe page turn",
    revealMechanic: "magazine-page-turn",
    sceneArchitecture:
      "Film title → Magazine cover → Page-turn chapters → Story spread → Film-strip collage → Details → RSVP → Credits page",
    motionProfile: "editorial",
    parallaxProfile: "subtle",
    typographySystem: "editorial-serif",
    buttonFamily: "editorial-underline",
    backgroundSystem: "velvet-night",
    mediaPresentationStyle: "magazine-collage",
    compatibleAudioCategories: ["jazz", "piano", "cinematic-ambient", "wedding"],
    prohibitedAudioCategories: ["party-edm", "drums", "memorial", "funeral"],
    soundEffectProfile: "page-turn",
    outroType: "credits-page",
    introVariant: "film-title",
    openingExperience: "magazine-page-turn",
    sceneTransition: "book",
    outroExperience: "credits-page",
    slideshowStyle: "magazine-collage",
    countdownStyle: "luxury",
    packageAccess: "premium",
    reducedMotionFallback: "static editorial spread with Continue",
    primaryActions: ["RSVP", "GALLERY", "SHARE", "SAVE_DATE", "COUNTDOWN", "LOCATION"],
    audioDirectorProfile: "midnight-jazz",
  },
  "memorial-candle-tribute": {
    creativeUniverse: "memorial-candle",
    creativeConcept: "Memorial Candle — soft light into unlit candle; tap to light; life timeline album",
    emotionalTone: "solemn",
    targetAudience: "Funerals and memorial gatherings",
    visualLanguage: "candle glow, restrained portrait framing, warm stone, life timeline, memory album",
    openingSequence: "celeventic candlelight fade → unlit candle → tap to light",
    revealMechanic: "candle-light",
    sceneArchitecture:
      "Soft light → Unlit candle → Light the flame → Obituary → Life timeline album → Tribute memory → Schedule → Candle-legacy outro",
    motionProfile: "solemn",
    parallaxProfile: "none",
    typographySystem: "memorial",
    buttonFamily: "solemn",
    backgroundSystem: "candle-stone",
    mediaPresentationStyle: "timeline-gallery",
    compatibleAudioCategories: ["memorial-piano", "memorial-violin", "choir-soft"],
    prohibitedAudioCategories: ["party", "edm", "celebration", "neon"],
    soundEffectProfile: "soft-chime",
    outroType: "candle-legacy",
    introVariant: "candlelight",
    openingExperience: "candle-light",
    sceneTransition: "fade",
    outroExperience: "candle-legacy",
    slideshowStyle: "timeline-gallery",
    countdownStyle: "minimal",
    packageAccess: "free",
    reducedMotionFallback: "static tribute card with Continue",
    primaryActions: ["RSVP", "GALLERY", "MEMORY_UPLOAD", "LOCATION", "SHARE", "CONTRIBUTION"],
    audioDirectorProfile: "memorial-piano",
  },
  "corporate-prestige-summit": {
    creativeUniverse: "corporate-prestige",
    creativeConcept: "Corporate Prestige — kinetic logo grid into title; scroll/tap agenda chapters",
    emotionalTone: "corporate",
    targetAudience: "Conferences, summits, and corporate events",
    visualLanguage: "refined grid, teal accents, precision kinetic type, glass parallax, speaker cards",
    openingSequence: "celeventic kinetic engine-grid → corporate curtain title",
    revealMechanic: "curtain-corporate",
    sceneArchitecture:
      "Kinetic logo grid → Title curtain → About → Speakers → Agenda chapters → Sponsors → Venue → Registration → Calendar share outro",
    motionProfile: "corporate",
    parallaxProfile: "moderate",
    typographySystem: "corporate-sans",
    buttonFamily: "corporate-solid",
    backgroundSystem: "grid-glass",
    mediaPresentationStyle: "split-media",
    compatibleAudioCategories: ["corporate-ambient", "modern-piano", "subtle-electronic"],
    prohibitedAudioCategories: ["romantic", "memorial", "party-edm"],
    soundEffectProfile: "soft-click",
    outroType: "see-you-soon",
    introVariant: "engine-grid",
    openingExperience: "curtain-corporate",
    sceneTransition: "slide",
    outroExperience: "see-you-soon",
    slideshowStyle: "split-media",
    countdownStyle: "glass",
    packageAccess: "premium",
    reducedMotionFallback: "static title card with Continue to agenda",
    primaryActions: ["RSVP", "SAVE_DATE", "SHARE", "LOCATION", "GALLERY", "QR_PASS"],
    audioDirectorProfile: "corporate-ambient",
  },

  // ─── Batch 1: funeral Wave-1 shared-layout SKUs ────────────────────────────
  "candlelight-farewell": {
    creativeUniverse: "memory-album",
    creativeConcept: "Chapel Candle Farewell — glass shimmer into a quiet curtain of remembrance",
    emotionalTone: "reverent",
    targetAudience: "Families announcing a celebration of life",
    visualLanguage: "warm candle wall, soft gold on stone, restrained page rhythm",
    openingSequence: "celeventic glass shimmer → soft award curtain",
    revealMechanic: "curtain-award",
    sceneArchitecture: "Glass shimmer → Soft curtain → Notice → Service details → Attendance → Memory thanks",
    motionProfile: "solemn",
    parallaxProfile: "none",
    typographySystem: "memorial-serif",
    buttonFamily: "outline",
    backgroundSystem: "candle-amber",
    mediaPresentationStyle: "classic-slideshow",
    compatibleAudioCategories: ["memorial-piano", "soft-ambient"],
    prohibitedAudioCategories: ["party", "edm", "neon", "drums-loud"],
    soundEffectProfile: "soft-page",
    outroType: "memory-slideshow",
    introVariant: "glass-shimmer",
    openingExperience: "curtain-award",
    sceneTransition: "fade",
    outroExperience: "memory-slideshow",
    slideshowStyle: "classic-slideshow",
    countdownStyle: "minimal",
    packageAccess: "free",
    reducedMotionFallback: "static candle notice with Continue",
  },
  "white-lily-rest": {
    creativeUniverse: "lily-serenity",
    creativeConcept: "White Lily Rest — ivory stillness with a floral envelope into quiet pages",
    emotionalTone: "serene",
    targetAudience: "Families preferring a clean, minimal memorial",
    visualLanguage: "ivory lily motifs, pale stone, whisper typography",
    openingSequence: "celeventic lily breathe → floral envelope",
    revealMechanic: "envelope-floral",
    sceneArchitecture: "Lily breathe → Floral envelope → Resting notice → Service → Attendance → Final quote",
    motionProfile: "minimal",
    parallaxProfile: "none",
    typographySystem: "lily-sans",
    buttonFamily: "minimal-text",
    backgroundSystem: "ivory-mist",
    mediaPresentationStyle: "fade-carousel",
    compatibleAudioCategories: ["strings-soft", "ambient-quiet"],
    prohibitedAudioCategories: ["party", "edm", "neon", "drums"],
    soundEffectProfile: "soft-breath",
    outroType: "final-quote",
    introVariant: "lily-breathe",
    openingExperience: "envelope-floral",
    sceneTransition: "fade",
    outroExperience: "final-quote",
    slideshowStyle: "fade-carousel",
    countdownStyle: "minimal",
    packageAccess: "free",
    reducedMotionFallback: "static ivory card with Continue",
  },
  "royal-mourning-lite": {
    creativeUniverse: "royal-mourning",
    creativeConcept: "Royal Mourning Lite — black-red-white drape into a press-hold rite",
    emotionalTone: "dignified",
    targetAudience: "Ghanaian families honouring funeral custom",
    visualLanguage: "mourning cloth, silver-on-black type, red honour accents",
    openingSequence: "celeventic drape fall → press and hold to open",
    revealMechanic: "press-hold",
    sceneArchitecture: "Drape fall → Press-hold unlock → Announcement → Rite details → Attendance → Final quote",
    motionProfile: "traditional",
    parallaxProfile: "none",
    typographySystem: "heritage-display",
    buttonFamily: "ribbon",
    backgroundSystem: "mourning-drape",
    mediaPresentationStyle: "split-media",
    compatibleAudioCategories: ["acoustic-warm", "choir-soft"],
    prohibitedAudioCategories: ["party", "edm", "neon", "celebration"],
    soundEffectProfile: "cloth-fold",
    outroType: "final-quote",
    introVariant: "drape-fall",
    openingExperience: "press-hold",
    sceneTransition: "door",
    outroExperience: "final-quote",
    slideshowStyle: "split-media",
    countdownStyle: "minimal",
    packageAccess: "free",
    reducedMotionFallback: "static mourning card with Continue",
  },
  "white-lily-memorial-pages": {
    creativeUniverse: "lily-serenity",
    creativeConcept: "White Lily Memorial Journey — aurora rise into a silver-seal tribute chapter",
    emotionalTone: "tender",
    targetAudience: "Premium memorial hosts wanting a full tribute arc",
    visualLanguage: "serene ivory chapters, lily dividers, soft portrait frames",
    openingSequence: "celeventic aurora rise → silver wax seal",
    revealMechanic: "wax-seal-silver",
    sceneArchitecture: "Aurora → Silver seal → Cover → Biography → Tribute gallery → Schedule → Attendance → Thanks",
    motionProfile: "solemn",
    parallaxProfile: "none",
    typographySystem: "lily-editorial",
    buttonFamily: "crystal",
    backgroundSystem: "ivory-chapter",
    mediaPresentationStyle: "polaroid-stack",
    compatibleAudioCategories: ["ambient-cinematic", "strings-soft"],
    prohibitedAudioCategories: ["party", "edm", "neon"],
    soundEffectProfile: "soft-chime",
    outroType: "thank-you-fade",
    introVariant: "aurora-rise",
    openingExperience: "wax-seal-silver",
    sceneTransition: "book",
    outroExperience: "thank-you-fade",
    slideshowStyle: "polaroid-stack",
    countdownStyle: "minimal",
    packageAccess: "premium",
    reducedMotionFallback: "static lily chapter with Continue",
  },

  // ─── Batch 2: classic browse layouts ───────────────────────────────────────
  "classic-gold": {
    creativeUniverse: "gilded-classic",
    creativeConcept: "Satin Bow — ivory parchment tied with a satin bow ceremony",
    emotionalTone: "romantic",
    targetAudience: "Classic romantic weddings",
    visualLanguage: "ivory card, satin ribbon folds, blush accents, soft foil names",
    openingSequence: "celeventic foil rise → untie satin bow",
    revealMechanic: "satin-bow",
    sceneArchitecture: "Foil rise → Satin bow untie → Couple → Vows → Gallery → RSVP → Petal outro",
    motionProfile: "romantic",
    parallaxProfile: "subtle",
    typographySystem: "romantic-script",
    buttonFamily: "ribbon",
    backgroundSystem: "ivory-parchment",
    mediaPresentationStyle: "floating-memories",
    compatibleAudioCategories: ["piano", "wedding", "strings-soft"],
    prohibitedAudioCategories: ["edm", "neon", "memorial", "funeral"],
    soundEffectProfile: "ribbon-soft",
    outroType: "rose-petals",
    introVariant: "foil-rise",
    openingExperience: "satin-bow",
    sceneTransition: "sparkle",
    outroExperience: "rose-petals",
    slideshowStyle: "floating-memories",
    countdownStyle: "ring",
    packageAccess: "free",
    reducedMotionFallback: "static ivory card with Continue",
  },
  "luxury-rings": {
    creativeUniverse: "luxury-black-tie",
    creativeConcept: "Luxury Black Tie — onyx stage, interlocking rings, ring-box reveal",
    emotionalTone: "luxurious",
    targetAudience: "Black-tie weddings and evening ceremonies",
    visualLanguage: "high-contrast black stage, gold rings, spotlight drama",
    openingSequence: "celeventic ring orbit → open ring box under spotlight",
    revealMechanic: "ring-box",
    sceneArchitecture: "Ring orbit → Ring box → Stage cover → Vows → Gallery film strip → RSVP → Fireworks",
    motionProfile: "luxurious",
    parallaxProfile: "cinematic",
    typographySystem: "display-luxury",
    buttonFamily: "gold",
    backgroundSystem: "onyx-stage",
    mediaPresentationStyle: "film-strip",
    compatibleAudioCategories: ["violin", "orchestra", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "edm-party"],
    soundEffectProfile: "spotlight-click",
    outroType: "fireworks",
    introVariant: "ring-orbit",
    openingExperience: "ring-box",
    sceneTransition: "curtain",
    outroExperience: "fireworks",
    slideshowStyle: "film-strip",
    countdownStyle: "luxury",
    packageAccess: "premium",
    reducedMotionFallback: "static onyx card with Continue",
  },
  "arch-green": {
    creativeUniverse: "architectural-romance",
    creativeConcept: "Vine Cathedral lite — palace doors into a living green arch",
    emotionalTone: "nature",
    targetAudience: "Garden and outdoor weddings",
    visualLanguage: "forest arch, emerald depth, cream calligraphy",
    openingSequence: "celeventic vine grow → palace entrance gates",
    revealMechanic: "palace-entrance",
    sceneArchitecture: "Vine grow → Palace gates → Arch cover → Story → Venue path → RSVP → Memory slideshow",
    motionProfile: "organic",
    parallaxProfile: "moderate",
    typographySystem: "nature-calligraphy",
    buttonFamily: "sharp",
    backgroundSystem: "forest-arch",
    mediaPresentationStyle: "floating-memories",
    compatibleAudioCategories: ["strings-garden", "acoustic", "wedding"],
    prohibitedAudioCategories: ["edm", "corporate", "neon", "funeral", "memorial"],
    soundEffectProfile: "leaf-rustle",
    outroType: "memory-slideshow",
    introVariant: "vine-grow",
    openingExperience: "palace-entrance",
    sceneTransition: "fade",
    outroExperience: "memory-slideshow",
    slideshowStyle: "floating-memories",
    countdownStyle: "classic",
    packageAccess: "free",
    reducedMotionFallback: "static arch card with Continue",
  },
  "rustic-lace": {
    creativeUniverse: "paper-craft",
    creativeConcept: "Swan Lake Romance — lace draw into a photo-develop chapter",
    emotionalTone: "storybook",
    targetAudience: "Rustic and traditional weddings",
    visualLanguage: "ornate lace overlay, warm timber, full-bleed portraits, paper tabs",
    openingSequence: "celeventic lace draw → zoom storybook",
    revealMechanic: "zoom-reveal",
    sceneArchitecture: "Lace draw → Zoom frame → Couple story → Gallery → RSVP → Memory outro",
    motionProfile: "traditional",
    parallaxProfile: "subtle",
    typographySystem: "rustic-serif",
    buttonFamily: "paper-tab",
    backgroundSystem: "timber-lace",
    mediaPresentationStyle: "polaroid-stack",
    compatibleAudioCategories: ["acoustic-warm", "folk", "wedding"],
    prohibitedAudioCategories: ["edm", "neon", "corporate", "funeral", "memorial"],
    soundEffectProfile: "paper-fold",
    outroType: "final-quote",
    introVariant: "lace-draw",
    openingExperience: "zoom-reveal",
    sceneTransition: "book",
    outroExperience: "final-quote",
    slideshowStyle: "polaroid-stack",
    countdownStyle: "classic",
    packageAccess: "premium",
    reducedMotionFallback: "static lace card with Continue",
  },
  "boho-hexagon": {
    creativeUniverse: "celebration-pop",
    creativeConcept: "Art Deco Wedding — gift-box pop into floating gold geometry",
    emotionalTone: "playful",
    targetAudience: "Engagements and free-spirited celebrations",
    visualLanguage: "soft florals, gold hexagon frame, deco lounge warmth",
    openingSequence: "celeventic hex assemble → gift box open",
    revealMechanic: "gift-box",
    sceneArchitecture: "Hex assemble → Gift box → Cover → Couple → Grid gallery → Share → Petals",
    motionProfile: "playful",
    parallaxProfile: "moderate",
    typographySystem: "boho-sans",
    buttonFamily: "rounded",
    backgroundSystem: "soft-hex",
    mediaPresentationStyle: "magazine-collage",
    compatibleAudioCategories: ["lounge", "acoustic-light", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "corporate"],
    soundEffectProfile: "soft-pop",
    outroType: "rose-petals",
    introVariant: "hex-assemble",
    openingExperience: "gift-box",
    sceneTransition: "sparkle",
    outroExperience: "rose-petals",
    slideshowStyle: "magazine-collage",
    countdownStyle: "ring",
    packageAccess: "free",
    reducedMotionFallback: "static hexagon card with Continue",
  },
  "floral-garden": {
    creativeUniverse: "botanical-romance",
    creativeConcept: "Watercolor Garden — petal cascade into blush botanical borders",
    emotionalTone: "romantic",
    targetAudience: "Weddings wanting botanical borders and blush type",
    visualLanguage: "blush typography, watercolor washes, botanical borders, petal drifts",
    openingSequence: "celeventic petal cascade → petal fall ceremony",
    revealMechanic: "petal-fall",
    sceneArchitecture: "Petal cascade → Petal fall → Garden cover → Gallery → Music → Calendar → Butterflies",
    motionProfile: "romantic",
    parallaxProfile: "moderate",
    typographySystem: "blush-script",
    buttonFamily: "pearl",
    backgroundSystem: "botanical-border",
    mediaPresentationStyle: "polaroid-stack",
    compatibleAudioCategories: ["garden-whispers", "piano-soft", "wedding"],
    prohibitedAudioCategories: ["edm", "corporate", "neon", "funeral", "memorial"],
    soundEffectProfile: "petal-soft",
    outroType: "butterflies",
    introVariant: "petal-cascade",
    openingExperience: "petal-fall",
    sceneTransition: "slide",
    outroExperience: "butterflies",
    slideshowStyle: "polaroid-stack",
    countdownStyle: "ring",
    packageAccess: "free",
    reducedMotionFallback: "static garden card with Continue",
  },

  // ─── Batch 3: remaining browse layouts ─────────────────────────────────────
  "passport-luxe": {
    creativeUniverse: "passport-destination",
    creativeConcept: "Tropical Destination — folio open into flip boarding booklet",
    emotionalTone: "wanderlust",
    targetAudience: "Destination and travel-themed weddings",
    visualLanguage: "visa stamps, booklet folds, teal passport covers",
    openingSequence: "celeventic folio open → flip passport",
    revealMechanic: "flip-reveal",
    sceneArchitecture: "Folio → Flip passport → Stamps → Itinerary → Maps → RSVP → Final quote",
    motionProfile: "dreamlike",
    parallaxProfile: "cinematic",
    typographySystem: "travel-mono",
    buttonFamily: "ticket-stub",
    backgroundSystem: "passport-teal",
    mediaPresentationStyle: "magazine-collage",
    compatibleAudioCategories: ["travel", "voyage", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "edm"],
    soundEffectProfile: "stamp-press",
    outroType: "final-quote",
    introVariant: "folio-open",
    openingExperience: "flip-reveal",
    sceneTransition: "door",
    outroExperience: "final-quote",
    slideshowStyle: "magazine-collage",
    countdownStyle: "classic",
    packageAccess: "premium",
    reducedMotionFallback: "static passport cover with Continue",
  },
  "glass-acrylic": {
    creativeUniverse: "crystal-glass",
    creativeConcept: "Cinematic Film Premiere — marble veil into 3-2-1 premiere countdown",
    emotionalTone: "cinematic",
    targetAudience: "Modern luxury weddings",
    visualLanguage: "frosted acrylic, teal depth, metallic edges, premiere countdown",
    openingSequence: "celeventic marble veil → film countdown",
    revealMechanic: "film-countdown",
    sceneArchitecture: "Marble veil → Film countdown → Frost cover → Depth gallery → Countdown → RSVP → Curtain close",
    motionProfile: "dreamlike",
    parallaxProfile: "interactive",
    typographySystem: "frost-sans",
    buttonFamily: "crystal",
    backgroundSystem: "frost-depth",
    mediaPresentationStyle: "floating-memories",
    compatibleAudioCategories: ["crystal-ambient", "harp", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "drums-loud"],
    soundEffectProfile: "glass-chime",
    outroType: "closing-curtain",
    introVariant: "marble-veil",
    openingExperience: "film-countdown",
    sceneTransition: "sparkle",
    outroExperience: "closing-curtain",
    slideshowStyle: "floating-memories",
    countdownStyle: "glass",
    packageAccess: "premium",
    reducedMotionFallback: "static frost card with Continue",
  },
  "kente-heritage-union": {
    creativeUniverse: "heritage-textile",
    creativeConcept: "Kente Covenant — ticket tear into a swipe of woven heritage",
    emotionalTone: "traditional",
    targetAudience: "Ghanaian and pan-African weddings",
    visualLanguage: "woven maroon-gold-emerald, grand lettering, drum rhythm",
    openingSequence: "celeventic ticket tear → woven cloth swipe reveal",
    revealMechanic: "swipe-reveal",
    sceneArchitecture: "Ticket tear → Swipe cloth → Covenant cover → Seating → Wishes → Gallery → Lanterns",
    motionProfile: "traditional",
    parallaxProfile: "moderate",
    typographySystem: "heritage-grand",
    buttonFamily: "kente",
    backgroundSystem: "kente-weave",
    mediaPresentationStyle: "magazine-collage",
    compatibleAudioCategories: ["african-drums", "celebration-strings", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "edm-neon"],
    soundEffectProfile: "drum-soft",
    outroType: "lanterns",
    introVariant: "ticket-tear",
    openingExperience: "swipe-reveal",
    sceneTransition: "book",
    outroExperience: "lanterns",
    slideshowStyle: "magazine-collage",
    countdownStyle: "classic",
    packageAccess: "premium",
    reducedMotionFallback: "static kente card with Continue",
  },
  "golden-islamic-nikkah": {
    creativeUniverse: "islamic-ornamental",
    creativeConcept: "Islamic Ornamental — quill script into geometric palace envelope",
    emotionalTone: "reverent",
    targetAudience: "Nikkah and Islamic wedding celebrations",
    visualLanguage: "gold geometry, emerald fields, ornamental arches, soft instrumental",
    openingSequence: "celeventic quill script → Islamic envelope",
    revealMechanic: "envelope-islamic",
    sceneArchitecture: "Quill → Islamic envelope → Geometry cover → Schedule → Venue → Maps → Sparkle outro",
    motionProfile: "traditional",
    parallaxProfile: "subtle",
    typographySystem: "ornamental-serif",
    buttonFamily: "wax-seal",
    backgroundSystem: "islamic-geometry",
    mediaPresentationStyle: "ken-burns",
    compatibleAudioCategories: ["instrumental-soft", "strings", "muslim", "wedding"],
    prohibitedAudioCategories: ["edm", "party", "neon", "funeral", "memorial"],
    soundEffectProfile: "soft-chime",
    outroType: "golden-sparkles",
    introVariant: "quill-script",
    openingExperience: "envelope-islamic",
    sceneTransition: "fade",
    outroExperience: "golden-sparkles",
    slideshowStyle: "ken-burns",
    countdownStyle: "circular",
    packageAccess: "free",
    reducedMotionFallback: "static geometric card with Continue",
  },
  "neon-celebration-party": {
    creativeUniverse: "neon-celebration",
    creativeConcept: "Electric Pulse — neon pulse into confetti burst party ticket",
    emotionalTone: "high-energy",
    targetAudience: "Birthdays and nightlife celebrations",
    visualLanguage: "fuchsia neon, scratch energy, ticket QR",
    openingSequence: "celeventic neon pulse → confetti burst",
    revealMechanic: "confetti-burst",
    sceneArchitecture: "Neon pulse → Confetti → Ticket cover → RSVP → QR → Share → Fireworks",
    motionProfile: "energetic",
    parallaxProfile: "interactive",
    typographySystem: "neon-display",
    buttonFamily: "neon",
    backgroundSystem: "neon-night",
    mediaPresentationStyle: "grid-reveal",
    compatibleAudioCategories: ["party-edm", "celebration"],
    prohibitedAudioCategories: ["memorial", "corporate", "solemn"],
    soundEffectProfile: "neon-zap",
    outroType: "fireworks",
    introVariant: "neon-pulse",
    openingExperience: "confetti-burst",
    sceneTransition: "slide",
    outroExperience: "fireworks",
    slideshowStyle: "grid-reveal",
    countdownStyle: "flip",
    packageAccess: "free",
    reducedMotionFallback: "static neon ticket with Continue",
  },
  "custom-media": {
    creativeUniverse: "custom-media",
    creativeConcept: "Your Canvas — canvas wipe into a foil-scratch media frame",
    emotionalTone: "creator-led",
    targetAudience: "Hosts uploading their own artwork, video, or PDF",
    visualLanguage: "cinematic media frame, teal studio field, creator freedom",
    openingSequence: "celeventic canvas wipe → scratch foil media reveal",
    revealMechanic: "scratch",
    sceneArchitecture: "Canvas wipe → Scratch → Media hero → Gallery → RSVP → Upload memories outro",
    motionProfile: "cinematic",
    parallaxProfile: "subtle",
    typographySystem: "studio-sans",
    buttonFamily: "gradient-cta",
    backgroundSystem: "studio-teal",
    mediaPresentationStyle: "fullscreen-video",
    compatibleAudioCategories: ["cinematic", "ambient"],
    prohibitedAudioCategories: [],
    soundEffectProfile: "ui-whoosh",
    outroType: "upload-memories",
    introVariant: "canvas-wipe",
    openingExperience: "scratch",
    sceneTransition: "fade",
    outroExperience: "upload-memories",
    slideshowStyle: "fullscreen-video",
    countdownStyle: "minimal",
    packageAccess: "free",
    reducedMotionFallback: "static media frame with Continue",
  },

  // ─── Batch 4: Wave-1 free + non-pilot flagship polish ──────────────────────
  "gilded-vows": {
    creativeUniverse: "gilded-classic",
    creativeConcept: "Storybook Romance — seal impress into an unfolding gilded letter",
    emotionalTone: "storybook",
    targetAudience: "Free-tier classic weddings",
    visualLanguage: "ivory pages, foil names, silver seal, flourish motifs",
    openingSequence: "celeventic seal impress → letter unfold",
    revealMechanic: "letter-unfold",
    sceneArchitecture: "Seal impress → Letter unfold → Cover → Names → Details → RSVP → Sparkles",
    motionProfile: "minimal",
    parallaxProfile: "none",
    typographySystem: "gilded-serif-lite",
    buttonFamily: "gold",
    backgroundSystem: "ivory-page",
    mediaPresentationStyle: "luxury-frame",
    compatibleAudioCategories: ["piano-romance", "wedding"],
    prohibitedAudioCategories: ["edm", "neon", "funeral", "memorial"],
    soundEffectProfile: "foil-soft",
    outroType: "golden-sparkles",
    introVariant: "seal-impress",
    openingExperience: "letter-unfold",
    sceneTransition: "door",
    outroExperience: "golden-sparkles",
    slideshowStyle: "luxury-frame",
    countdownStyle: "gold-royal",
    packageAccess: "free",
    reducedMotionFallback: "static vows page with Continue",
  },
  "emerald-promise": {
    creativeUniverse: "architectural-romance",
    creativeConcept: "Celestial Love — chapel glow into a rose-gold seal under starlight",
    emotionalTone: "hopeful",
    targetAudience: "Free-tier botanical weddings",
    visualLanguage: "deep emerald pages, cream calligraphy, starlit botanical dividers",
    openingSequence: "celeventic chapel glow → rose gold seal",
    revealMechanic: "wax-seal-rose",
    sceneArchitecture: "Chapel glow → Rose seal → Cover → Details → Maps → RSVP → Butterflies",
    motionProfile: "minimal",
    parallaxProfile: "none",
    typographySystem: "emerald-calligraphy",
    buttonFamily: "outline",
    backgroundSystem: "emerald-page",
    mediaPresentationStyle: "fade-carousel",
    compatibleAudioCategories: ["strings-garden", "wedding"],
    prohibitedAudioCategories: ["edm", "neon", "funeral", "memorial"],
    soundEffectProfile: "leaf-soft",
    outroType: "butterflies",
    introVariant: "chapel-glow",
    openingExperience: "wax-seal-rose",
    sceneTransition: "book",
    outroExperience: "butterflies",
    slideshowStyle: "fade-carousel",
    countdownStyle: "classic",
    packageAccess: "free",
    reducedMotionFallback: "static emerald page with Continue",
  },
  "kente-court": {
    creativeUniverse: "heritage-textile",
    creativeConcept: "Kente Court — drum pulse into a joyful pop reveal",
    emotionalTone: "celebratory",
    targetAudience: "Free-tier heritage weddings",
    visualLanguage: "maroon and gold pages, grand lettering, court drums",
    openingSequence: "celeventic drum pulse → pop reveal",
    revealMechanic: "pop-reveal",
    sceneArchitecture: "Drum pulse → Pop reveal → Court cover → Details → Maps → RSVP → Fireworks",
    motionProfile: "traditional",
    parallaxProfile: "none",
    typographySystem: "court-display",
    buttonFamily: "metallic",
    backgroundSystem: "court-maroon",
    mediaPresentationStyle: "polaroid-stack",
    compatibleAudioCategories: ["african-drums", "wedding"],
    prohibitedAudioCategories: ["edm", "memorial", "funeral"],
    soundEffectProfile: "drum-soft",
    outroType: "fireworks",
    introVariant: "drum-pulse",
    openingExperience: "pop-reveal",
    sceneTransition: "slide",
    outroExperience: "fireworks",
    slideshowStyle: "polaroid-stack",
    countdownStyle: "classic",
    packageAccess: "free",
    reducedMotionFallback: "static court page with Continue",
  },
  "gilded-opulence-pages": {
    creativeUniverse: "gilded-classic",
    creativeConcept: "European Manor — royal orbit into gold wax with parallax foil gallery",
    emotionalTone: "regal",
    targetAudience: "Premium paged gilded weddings",
    visualLanguage: "ivory parchment, foil medallions, parallax cover drift",
    openingSequence: "celeventic royal orbit → gold wax seal",
    revealMechanic: "wax-seal-gold",
    sceneArchitecture: "Orbit → Gold seal → Parallax cover → Gallery pages → Venue → RSVP → Curtain close",
    motionProfile: "cinematic",
    parallaxProfile: "cinematic",
    typographySystem: "opulence-serif",
    buttonFamily: "embossed-royal",
    backgroundSystem: "foil-parallax",
    mediaPresentationStyle: "luxury-frame",
    compatibleAudioCategories: ["orchestra-royal", "wedding"],
    prohibitedAudioCategories: ["edm", "neon", "funeral", "memorial"],
    soundEffectProfile: "seal-press",
    outroType: "closing-curtain",
    introVariant: "orbit",
    openingExperience: "wax-seal-gold",
    sceneTransition: "door",
    outroExperience: "closing-curtain",
    slideshowStyle: "luxury-frame",
    countdownStyle: "gold-royal",
    packageAccess: "premium",
    reducedMotionFallback: "static opulence page with Continue",
  },
  "emerald-cathedral": {
    creativeUniverse: "architectural-romance",
    creativeConcept: "Palace Gates — constellation into emerald archway gates",
    emotionalTone: "regal",
    targetAudience: "Premium arched botanical weddings",
    visualLanguage: "cathedral arches, living vines, dusk-lit emerald depths",
    openingSequence: "celeventic constellation → archway gates",
    revealMechanic: "archway",
    sceneArchitecture: "Constellation → Archway → Arch cover → Vine journey → Polaroids → RSVP → Butterflies",
    motionProfile: "romantic",
    parallaxProfile: "moderate",
    typographySystem: "cathedral-elegant",
    buttonFamily: "ornamental-arch",
    backgroundSystem: "nave-emerald",
    mediaPresentationStyle: "polaroid-stack",
    compatibleAudioCategories: ["strings-crystal", "garden", "wedding"],
    prohibitedAudioCategories: ["edm", "neon", "funeral", "memorial"],
    soundEffectProfile: "vine-soft",
    outroType: "butterflies",
    introVariant: "constellation",
    openingExperience: "archway",
    sceneTransition: "book",
    outroExperience: "butterflies",
    slideshowStyle: "polaroid-stack",
    countdownStyle: "classic",
    packageAccess: "premium",
    reducedMotionFallback: "static cathedral page with Continue",
  },
  "kente-royale-pages": {
    creativeUniverse: "heritage-textile",
    creativeConcept: "Kente Royale — soft intro into theatrical velvet curtains with kente gold trim",
    emotionalTone: "traditional",
    targetAudience: "Premium royal kente weddings",
    visualLanguage: "woven maroon and gold, grand lettering, stage curtain reveal",
    openingSequence: "celeventic soft intro → wedding stage curtains part (touch to begin)",
    revealMechanic: "curtain-wedding",
    sceneArchitecture: "Soft intro → Curtain stage → Royale cover → Weave gallery → Venue → RSVP → Golden sparkles",
    motionProfile: "cinematic",
    parallaxProfile: "cinematic",
    typographySystem: "royale-traditional",
    buttonFamily: "kente",
    backgroundSystem: "royale-weave",
    mediaPresentationStyle: "stacked-cards",
    compatibleAudioCategories: ["drums-strings", "celebration", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "edm"],
    soundEffectProfile: "weave-soft",
    outroType: "golden-sparkles",
    introVariant: "ink-reveal",
    openingExperience: "curtain-wedding",
    sceneTransition: "book",
    outroExperience: "golden-sparkles",
    slideshowStyle: "stacked-cards",
    countdownStyle: "classic",
    packageAccess: "premium",
    reducedMotionFallback: "static royale page with Continue",
  },
  "candlelight-elegy-pages": {
    creativeUniverse: "memorial-candle",
    creativeConcept: "Candlelight Tribute Chapters — spotlight into light-beam elegy",
    emotionalTone: "solemn",
    targetAudience: "Premium memorial hosts needing biography chapters",
    visualLanguage: "candlelit darkness, warm gold on velvet black, portrait framing",
    openingSequence: "celeventic spotlight → light beam",
    revealMechanic: "light-beam",
    sceneArchitecture: "Spotlight → Light beam → Cover → Biography → Tribute → Schedule → Attendance → Thanks",
    motionProfile: "solemn",
    parallaxProfile: "none",
    typographySystem: "elegy-funeral",
    buttonFamily: "minimal-text",
    backgroundSystem: "elegy-velvet",
    mediaPresentationStyle: "classic-slideshow",
    compatibleAudioCategories: ["memorial-violin"],
    prohibitedAudioCategories: ["party", "edm", "neon"],
    soundEffectProfile: "beam-soft",
    outroType: "thank-you-fade",
    introVariant: "spotlight",
    openingExperience: "light-beam",
    sceneTransition: "fade",
    outroExperience: "thank-you-fade",
    slideshowStyle: "classic-slideshow",
    countdownStyle: "minimal",
    packageAccess: "premium",
    reducedMotionFallback: "static elegy page with Continue",
  },
  "royal-mourning-pages": {
    creativeUniverse: "royal-mourning",
    creativeConcept: "Royal Mourning Estate — light sweep into parchment scroll rite",
    emotionalTone: "dignified",
    targetAudience: "Full black-red-white Ghanaian funeral rites",
    visualLanguage: "velvet drape, silver-on-black typography, mourning cloth",
    openingSequence: "celeventic light sweep → parchment scroll",
    revealMechanic: "scroll-unroll",
    sceneArchitecture: "Light sweep → Scroll → Estate cover → Family → Tribute → Attendance → Final quote",
    motionProfile: "solemn",
    parallaxProfile: "none",
    typographySystem: "estate-elegant",
    buttonFamily: "metallic",
    backgroundSystem: "estate-drape",
    mediaPresentationStyle: "split-media",
    compatibleAudioCategories: ["funeral-choir", "jazz-soft"],
    prohibitedAudioCategories: ["party", "edm", "neon"],
    soundEffectProfile: "scroll-unroll",
    outroType: "final-quote",
    introVariant: "light-sweep",
    openingExperience: "scroll-unroll",
    sceneTransition: "door",
    outroExperience: "final-quote",
    slideshowStyle: "split-media",
    countdownStyle: "minimal",
    packageAccess: "premium",
    reducedMotionFallback: "static estate page with Continue",
  },
  "passport-destination-wedding": {
    creativeUniverse: "passport-destination",
    creativeConcept: "Horizon Boarding Pass — fabric unfold into passport stamp journey",
    emotionalTone: "wanderlust",
    targetAudience: "Destination celebrations",
    visualLanguage: "boarding pass folds, visa stamps, horizon light",
    openingSequence: "celeventic fabric unfold → passport stamp",
    revealMechanic: "passport",
    sceneArchitecture: "Fabric → Passport → Boarding → Itinerary timeline → Maps → RSVP → See you soon",
    motionProfile: "dreamlike",
    parallaxProfile: "cinematic",
    typographySystem: "boarding-editorial",
    buttonFamily: "passport-stamp",
    backgroundSystem: "horizon-pass",
    mediaPresentationStyle: "timeline-gallery",
    compatibleAudioCategories: ["travel-guitar", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "edm"],
    soundEffectProfile: "stamp",
    outroType: "see-you-soon",
    introVariant: "fabric-unfold",
    openingExperience: "passport",
    sceneTransition: "slide",
    outroExperience: "see-you-soon",
    slideshowStyle: "timeline-gallery",
    countdownStyle: "classic",
    packageAccess: "premium",
    reducedMotionFallback: "static boarding pass with Continue",
  },
  "crystal-acrylic-luxury": {
    creativeUniverse: "crystal-glass",
    creativeConcept: "Champagne Crystal — prism refract into glass wipe with champagne light",
    emotionalTone: "luminous",
    targetAudience: "Luxury acrylic weddings",
    visualLanguage: "frosted depth, refraction, champagne gold edges",
    openingSequence: "celeventic prism refract → glass wipe",
    revealMechanic: "glass",
    sceneArchitecture: "Prism → Glass wipe → Crystal cover → Luxury frames → Countdown → RSVP → Memory shimmer",
    motionProfile: "luxurious",
    parallaxProfile: "cinematic",
    typographySystem: "crystal-minimal",
    buttonFamily: "glass",
    backgroundSystem: "champagne-prism",
    mediaPresentationStyle: "luxury-frame",
    compatibleAudioCategories: ["harp-ambient", "wedding"],
    prohibitedAudioCategories: ["memorial", "funeral", "edm"],
    soundEffectProfile: "prism-chime",
    outroType: "memory-slideshow",
    introVariant: "prism-refract",
    openingExperience: "glass",
    sceneTransition: "sparkle",
    outroExperience: "memory-slideshow",
    slideshowStyle: "luxury-frame",
    countdownStyle: "glass",
    packageAccess: "premium",
    reducedMotionFallback: "static crystal card with Continue",
  },
};
