import type { GuideCatalogEntry, GuideStepSeed } from "./types";

function steps(...items: Array<[string, string] | GuideStepSeed>): GuideStepSeed[] {
  return items.map((item, i) => {
    if (Array.isArray(item)) {
      return { title: item[0], body: item[1], stepType: "motion" as const, motionKey: `step-${i + 1}` };
    }
    return item;
  });
}

/**
 * §§51–62 completeness additions — only real product surfaces.
 * Merged by slug (later wins) so we don't duplicate parallel agent inventory.
 */
export const CELEVENTIC_GUIDE_COMPLETENESS_ADDITIONS: GuideCatalogEntry[] = [
  {
    slug: "organizer-quick-start",
    title: "Organizer Quick Start",
    summary: "Create an event, build an invitation, add guests, and prepare admission.",
    role: "ORGANIZER",
    category: "GETTING_STARTED",
    status: "PUBLISHED",
    sortOrder: 38,
    featured: true,
    featureKey: "organizer-quick-start",
    videoProductionRequired: true,
    durationSec: 55,
    storyboardKey: "organizer-quick-start",
    captionsEnUrl: "/guides/captions/organizer-quick-start.en.vtt",
    captionsFrUrl: "/guides/captions/organizer-quick-start.fr.vtt",
    synonyms: ["getting started organizer", "first event", "quick start"],
    contextRoutes: ["/dashboard/getting-started", "/dashboard/events"],
    relatedSlugs: ["create-an-event", "build-an-invitation", "add-guests"],
    posterUrl: "/guides/posters/create-event.svg",
    thumbnailUrl: "/guides/posters/create-event.svg",
    a11yDescription: "Organizer onboarding from create event to QR admission readiness.",
    narrationScript:
      "Create your event. Build a branded invitation. Add or import guests. Generate QR identities. Publish Event Guide.",
    transcript:
      "Create your event. Build a branded invitation. Add or import guests. Generate QR identities. Publish Event Guide.",
    steps: steps(
      ["Create event", "Pick type — wedding, corporate, birthday, and more."],
      ["Build invitation", "Choose a template and personalise."],
      ["Add guests", "Import or add manually, then send links."],
      ["Prepare admission", "Generate QR identities and open QR Hub."]
    ),
  },
  {
    slug: "tickets-organizer",
    title: "Tickets",
    summary: "Create ticket types, sell or issue tickets, and connect them to admission.",
    role: "ORGANIZER",
    category: "TICKETS",
    status: "PUBLISHED",
    sortOrder: 39,
    featureKey: "tickets",
    synonyms: ["ticketing", "ticket types", "sell tickets", "tickets overview"],
    contextRoutes: ["/dashboard/tickets"],
    relatedSlugs: ["tickets-overview", "payments-overview", "qr-admission-organizer"],
    posterUrl: "/guides/posters/admission.svg",
    steps: steps(
      ["Open Tickets", "From the dashboard, open Tickets for your event."],
      ["Define types", "Set quantities, prices, and tiers."],
      ["Issue or sell", "Share purchase or registration links."]
    ),
  },
  {
    slug: "gifts-organizer",
    title: "Gifts (Organizer)",
    summary: "Set up a gift campaign so guests can contribute digitally.",
    role: "ORGANIZER",
    category: "GIFTS",
    status: "PUBLISHED",
    sortOrder: 41,
    featureKey: "gifts",
    synonyms: ["gift wallet", "organizer gifts"],
    contextRoutes: ["/dashboard/gifts"],
    relatedSlugs: ["organizer-gifts", "guest-gifts", "wallet-organizer"],
    posterUrl: "/guides/posters/thank-you-org.svg",
    steps: steps(
      ["Create campaign", "Open Gifts and enable a public gift link."],
      ["Share with guests", "Add the gift link to invitations or messages."],
      ["Review & withdraw", "Track gifts from Wallet where available."]
    ),
  },
  {
    slug: "gifts-guest",
    title: "Send a Gift",
    summary: "How guests send a digital gift through Celeventic.",
    role: "GUEST",
    category: "GIFTS",
    status: "PUBLISHED",
    sortOrder: 42,
    featureKey: "gifts",
    synonyms: ["send gift", "guest gifts"],
    relatedSlugs: ["guest-gifts", "gifts-organizer"],
    posterUrl: "/guides/posters/thank-you.svg",
    steps: steps(
      ["Open the gift link", "Use the secure link from your host."],
      ["Choose amount", "Add an optional note."],
      ["Confirm payment", "Keep the receipt link for your records."]
    ),
  },
  {
    slug: "marketplace-organizer",
    title: "Marketplace",
    summary: "Discover vendors, request quotes, and manage bookings.",
    role: "ORGANIZER",
    category: "MARKETPLACE",
    status: "PUBLISHED",
    sortOrder: 43,
    featureKey: "marketplace",
    synonyms: ["find vendors", "marketplace basics"],
    contextRoutes: ["/marketplace", "/dashboard/discovery"],
    relatedSlugs: ["marketplace-basics", "venues-organizer", "vendor-portal"],
    posterUrl: "/guides/posters/vendor-passes.svg",
    steps: steps(
      ["Browse Marketplace", "Filter by category and location."],
      ["Request a quote", "Message vendors with your event details."],
      ["Track bookings", "Manage quotes and bookings from your dashboard."]
    ),
  },
  {
    slug: "vendor-portal",
    title: "Vendor Portal",
    summary: "Manage portfolio, availability, quotes, and bookings as a vendor.",
    role: "VENDOR",
    category: "VENDOR",
    status: "PUBLISHED",
    sortOrder: 44,
    featureKey: "vendor-portal",
    synonyms: ["vendor dashboard", "vendor onboarding"],
    contextRoutes: ["/dashboard/vendor-portal"],
    relatedSlugs: ["vendor-pass", "marketplace-organizer"],
    posterUrl: "/guides/posters/vendor-pass.svg",
    steps: steps(
      ["Complete profile", "Portfolio, services, and availability."],
      ["Respond to leads", "Send quotes and confirm bookings."],
      ["Event day", "Use your vendor pass for entry."]
    ),
  },
  {
    slug: "venues-organizer",
    title: "Venues",
    summary: "Find and manage venues for your event.",
    role: "ORGANIZER",
    category: "MARKETPLACE",
    status: "PUBLISHED",
    sortOrder: 45,
    featureKey: "venues",
    synonyms: ["venue booking", "find venue"],
    contextRoutes: ["/dashboard/venues"],
    relatedSlugs: ["marketplace-organizer", "seating-organizer"],
    posterUrl: "/guides/posters/seating-org.svg",
    steps: steps(
      ["Open Venues", "Browse available venues."],
      ["Check availability", "Align dates with your event."],
      ["Connect to seating", "Use venue layout cues when planning seats."]
    ),
  },
  {
    slug: "wallet-organizer",
    title: "Wallet & Payouts",
    summary: "Track revenue, gifts, and withdrawal requests.",
    role: "ORGANIZER",
    category: "WALLET",
    status: "PUBLISHED",
    sortOrder: 46,
    featureKey: "wallet",
    synonyms: ["payouts", "revenue", "withdrawals"],
    contextRoutes: ["/dashboard/wallet"],
    relatedSlugs: ["gifts-organizer", "payments-overview"],
    posterUrl: "/guides/posters/create-event.svg",
    steps: steps(
      ["Open Wallet", "Review balances and recent activity."],
      ["Request payout", "Submit a withdrawal when eligible."],
      ["Reconcile", "Cross-check gifts, tickets, and marketplace payouts."]
    ),
  },
  {
    slug: "contributions-organizer",
    title: "Contributions",
    summary: "Collect contributions for weddings, funerals, and community events.",
    role: "ORGANIZER",
    category: "CONTRIBUTIONS",
    status: "PUBLISHED",
    sortOrder: 47,
    featureKey: "contributions",
    synonyms: ["contribution list", "fundraising"],
    contextRoutes: ["/dashboard/contributions"],
    relatedSlugs: ["gifts-organizer", "event-os-funeral"],
    posterUrl: "/guides/posters/wishes-org.svg",
    steps: steps(
      ["Enable contributions", "Open Contributions for your event."],
      ["Share the link", "Invite guests or community members."],
      ["Acknowledge", "Thank contributors via messages or thank-you pages."]
    ),
  },
  {
    slug: "qr-hub",
    title: "QR & Pass Hub",
    summary: "Central place for guest passes, Event Guide QR, vendor passes, and print packs.",
    role: "ORGANIZER",
    category: "ADMISSION",
    status: "PUBLISHED",
    sortOrder: 48,
    featureKey: "qr-hub",
    synonyms: ["qr center", "pass hub", "print passes"],
    contextRoutes: ["/dashboard/qr-hub"],
    relatedSlugs: ["generate-qr-identities", "event-guide-qr", "vendor-passes-organizer"],
    posterUrl: "/guides/posters/guide-qr.svg",
    steps: steps(
      ["Open QR Hub", "Select your event."],
      ["Generate identities", "Create guest and vendor pass QRs."],
      ["Share or print", "Distribute Event Guide and admission QRs."]
    ),
  },
  {
    slug: "communications-organizer",
    title: "Communications",
    summary: "Message guests and run email, SMS, or WhatsApp campaigns.",
    role: "ORGANIZER",
    category: "COMMUNICATIONS",
    status: "PUBLISHED",
    sortOrder: 49,
    featureKey: "communications",
    synonyms: ["messages", "campaigns"],
    contextRoutes: ["/dashboard/messages", "/dashboard/campaigns"],
    relatedSlugs: ["add-guests"],
    posterUrl: "/guides/posters/group-org.svg",
    steps: steps(
      ["Open Messages or Campaigns", "Pick the channel that fits."],
      ["Segment guests", "Use tags and RSVP status."],
      ["Send thoughtfully", "Confirm content before blasting."]
    ),
  },
  {
    slug: "collaboration-workspace",
    title: "Collaboration Workspace",
    summary: "Invite collaborators, assign tasks, and track activity.",
    role: "ORGANIZER",
    category: "COLLABORATION",
    status: "PUBLISHED",
    sortOrder: 50,
    featureKey: "collaboration",
    synonyms: ["collaborators", "team workspace"],
    contextRoutes: ["/dashboard/events"],
    relatedSlugs: ["organizer-quick-start"],
    posterUrl: "/guides/posters/create-event.svg",
    steps: steps(
      ["Open Workspace", "From your event, open Collaborators / Workspace."],
      ["Invite teammates", "Assign roles and permissions."],
      ["Track tasks", "Use activity and tasks to stay aligned."]
    ),
  },
  {
    slug: "privacy-security",
    title: "Privacy & Security",
    summary: "Manage consent, privacy preferences, and account security.",
    role: "ORGANIZER",
    category: "PRIVACY",
    status: "PUBLISHED",
    sortOrder: 51,
    featureKey: "privacy",
    synonyms: ["privacy center", "privacy and data"],
    contextRoutes: ["/dashboard/privacy-center", "/dashboard/settings"],
    relatedSlugs: ["privacy-and-data", "settings-overview"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Open Privacy Center", "Review consents and data preferences."],
      ["Secure your account", "Enable available security options in Settings."],
      ["Respect guests", "Only share what your guests agreed to."]
    ),
  },
  {
    slug: "event-os-wedding",
    title: "Event OS — Wedding",
    summary: "Wedding blueprint on shared event routes: invitations, guests, seating, Event Guide.",
    role: "ORGANIZER",
    category: "PLATFORM",
    status: "PUBLISHED",
    sortOrder: 52,
    featureKey: "event-os-wedding",
    synonyms: ["wedding os", "wedding blueprint"],
    contextRoutes: ["/dashboard/events"],
    relatedSlugs: ["event-guide-organizer", "seating-organizer"],
    posterUrl: "/guides/posters/event-guide-org.svg",
    steps: steps(
      ["Create a wedding event", "Choose the Wedding event type."],
      ["Use wedding workspace", "Invitations, guests, seating, Event Guide, thank-you."],
      ["Day-of tools", "QR admission, companion, and Memory Vault."]
    ),
  },
  {
    slug: "event-os-funeral",
    title: "Event OS — Funeral / Memorial",
    summary: "FuneralOS: tributes, contributions, livestream, legacy, and memorial pages.",
    role: "ORGANIZER",
    category: "PLATFORM",
    status: "PUBLISHED",
    sortOrder: 53,
    featureKey: "event-os-funeral",
    synonyms: ["funeralos", "memorial"],
    contextRoutes: ["/dashboard/funeral"],
    relatedSlugs: ["contributions-organizer", "memory-vault-organizer"],
    posterUrl: "/guides/posters/memory-org.svg",
    steps: steps(
      ["Open FuneralOS", "From the organizer dashboard Funeral module."],
      ["Set memorial content", "Tributes, programme, livestream as needed."],
      ["Invite gently", "Share memorial and contribution links with care."]
    ),
  },
  {
    slug: "event-os-corporate",
    title: "Event OS — Corporate / Conference",
    summary: "Corporate and conference blueprints: registration, ticketing, and communications.",
    role: "ORGANIZER",
    category: "PLATFORM",
    status: "PUBLISHED",
    sortOrder: 54,
    featureKey: "event-os-corporate",
    synonyms: ["corporate event", "conference os"],
    contextRoutes: ["/dashboard/events"],
    relatedSlugs: ["tickets-organizer", "communications-organizer"],
    posterUrl: "/guides/posters/admission.svg",
    steps: steps(
      ["Create corporate/conference event", "Select the matching event type."],
      ["Registration & tickets", "Use guests and ticketing tools."],
      ["Run the day", "QR admission, Event Guide, and communications."]
    ),
  },
  {
    slug: "design-studio",
    title: "Design Studio & Inspiration",
    summary: "Design invitations, flyers, and explore AI-assisted inspiration.",
    role: "ORGANIZER",
    category: "PLATFORM",
    status: "PUBLISHED",
    sortOrder: 55,
    featureKey: "design-studio",
    synonyms: ["design studio", "inspiration"],
    contextRoutes: ["/dashboard/design-studio", "/dashboard/inspiration"],
    relatedSlugs: ["build-an-invitation"],
    posterUrl: "/guides/posters/build-invite.svg",
    steps: steps(
      ["Open Design Studio", "Start from templates or blank canvases."],
      ["Use Inspiration", "Upload mood references when helpful."],
      ["Publish to invitation", "Connect designs into Invitation Studio."]
    ),
  },
  {
    slug: "settings-overview",
    title: "Settings",
    summary: "Team, billing, profile, and preferences.",
    role: "ORGANIZER",
    category: "PLATFORM",
    status: "PUBLISHED",
    sortOrder: 56,
    featureKey: "settings",
    synonyms: ["account settings", "billing tab"],
    contextRoutes: ["/dashboard/settings"],
    relatedSlugs: ["privacy-security", "payments-overview"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Open Settings", "Use tabs for profile, team, and billing."],
      ["Invite team", "Add collaborators with the right access."],
      ["Review billing", "Packages and payment methods live here."]
    ),
  },
  {
    slug: "troubleshoot-weak-internet",
    title: "Weak internet",
    summary: "Keep celebration tools working on poor connectivity.",
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 65,
    featureKey: "troubleshoot-offline",
    synonyms: ["no wifi", "offline", "slow network"],
    relatedSlugs: ["offline-admission", "your-qr-admission-pass"],
    posterUrl: "/guides/posters/offline-admission.svg",
    steps: steps(
      { title: "Save your pass early", body: "Screenshot QR passes before you arrive.", stepType: "checklist" },
      { title: "Prefer mobile data", body: "Venue Wi‑Fi is often congested.", stepType: "tip" },
      { title: "Staff offline mode", body: "Scanners can admit offline and sync later.", stepType: "warning" }
    ),
  },
  {
    slug: "troubleshoot-memory-upload-failed",
    title: "Memory upload failed",
    summary: "Fix failed photo uploads to Memory Vault.",
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 66,
    featureKey: "troubleshoot-memory",
    synonyms: ["upload error", "photo failed"],
    relatedSlugs: ["memory-vault-guest", "troubleshoot-weak-internet"],
    posterUrl: "/guides/posters/memory.svg",
    steps: steps(
      { title: "Check size & format", body: "Use common photo formats; try a smaller image.", stepType: "checklist" },
      { title: "Stable connection", body: "Retry on Wi‑Fi.", stepType: "tip" },
      { title: "Ask host", body: "Uploads may be closed or moderated.", stepType: "warning" }
    ),
  },
  {
    slug: "troubleshoot-payment-pending",
    title: "Payment pending",
    summary: "What organizers should do when a payment stays pending.",
    role: "ORGANIZER",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 67,
    featureKey: "troubleshoot-payment",
    synonyms: ["payment stuck", "checkout pending"],
    relatedSlugs: ["payments-overview", "wallet-organizer"],
    posterUrl: "/guides/posters/create-event.svg",
    steps: steps(
      { title: "Wait briefly", body: "Provider confirmations can take a few minutes.", stepType: "checklist" },
      { title: "Do not double-pay", body: "Refresh status instead of starting a second checkout.", stepType: "warning" },
      { title: "Contact support", body: "Share the order reference only — never card details.", stepType: "tip" }
    ),
  },
  {
    slug: "troubleshoot-ticket-not-received",
    title: "Ticket not received",
    summary: "Find a missing ticket after purchase or registration.",
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 68,
    featureKey: "troubleshoot-ticket",
    synonyms: ["missing ticket", "no ticket email"],
    relatedSlugs: ["tickets-organizer", "your-qr-admission-pass"],
    posterUrl: "/guides/posters/qr-pass.svg",
    steps: steps(
      { title: "Check spam & original link", body: "Look for the confirmation message.", stepType: "checklist" },
      { title: "Use the event link", body: "Tickets may live on the invitation or pass page.", stepType: "tip" },
      { title: "Ask the organizer", body: "They can resend from Tickets / Guests.", stepType: "warning" }
    ),
  },
  {
    slug: "troubleshoot-vendor-pass",
    title: "Vendor pass not working",
    summary: "Fix vendor or team pass entry issues.",
    role: "VENDOR",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 69,
    featureKey: "troubleshoot-vendor-pass",
    synonyms: ["vendor qr fail", "crew pass invalid"],
    relatedSlugs: ["vendor-pass", "vendor-team-pass"],
    posterUrl: "/guides/posters/vendor-pass.svg",
    steps: steps(
      { title: "Confirm the right event", body: "Open the pass link issued for this event only.", stepType: "checklist" },
      { title: "Check validity window", body: "Some passes are time-bound for load-in.", stepType: "tip" },
      { title: "Ask organizer", body: "They can reissue from QR Hub.", stepType: "warning" }
    ),
  },
];
