import type { GuideCatalogEntry, GuideStepSeed } from "./types";

function steps(...items: Array<[string, string] | GuideStepSeed>): GuideStepSeed[] {
  return items.map((item, i) => {
    if (Array.isArray(item)) {
      return { title: item[0], body: item[1], stepType: "motion" as const, motionKey: `step-${i + 1}` };
    }
    return item;
  });
}

/** §63 guest catalog additions + plain-language overrides. */
export const GUEST_ZERO_CATALOG_ADDITIONS: GuideCatalogEntry[] = [
  {
    slug: "welcome-to-celeventic",
    title: "Welcome to Celeventic",
    summary: "First time here? This is your invitation helper — no app to install.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "GETTING_STARTED",
    status: "PUBLISHED",
    sortOrder: 1,
    featured: true,
    videoUrl: null,
    storyboardKey: "guest-zero-intro",
    synonyms: ["getting started guest", "new guest", "first time", "show me around"],
    relatedSlugs: ["how-celeventic-works", "open-your-invitation"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Open the link", "Use the invitation link you received — nothing to install."],
      ["Reply (RSVP)", "Tell the host if you are coming."],
      ["Keep your pass", "Your QR is on this same page for event day."],
      ["Need help?", "Tap the help chips or open Celeventic Guide."],
    ),
  },
  {
    slug: "open-your-invitation",
    title: "Open Your Invitation",
    summary: "Tap your link to see who invited you, when, and where.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "INVITATIONS",
    status: "PUBLISHED",
    sortOrder: 2,
    videoUrl: null,
    synonyms: ["open invite", "view invitation", "where is my invitation"],
    relatedSlugs: ["rsvp", "your-qr-admission-pass", "return-to-invitation"],
    posterUrl: "/guides/posters/invitation.svg",
    steps: steps(
      ["Tap the link", "Open it from WhatsApp, SMS, or email."],
      ["Read who invited you", "Check the host, date, and place."],
      ["Sound is optional", "You can continue with sound off."],
      ["Continue", "Next, reply with RSVP or find Your Pass."],
    ),
  },
  {
    slug: "rsvp",
    title: "RSVP",
    summary: "RSVP means please reply — Accept, Decline, or Maybe.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "RSVP",
    status: "PUBLISHED",
    sortOrder: 3,
    videoUrl: null,
    storyboardKey: "guest-accept-decline",
    synonyms: ["respond", "attending", "what does rsvp mean"],
    relatedSlugs: ["accept-or-decline", "choose-party-size"],
    posterUrl: "/guides/posters/rsvp.svg",
    steps: steps(
      ["Choose your reply", "Accept if you will come, Decline if not, Maybe if unsure."],
      ["Set party size", "Only count people the host allowed."],
      ["Save", "Wait for the thank-you confirmation."],
      ["Change later", "Reopen this link to update your RSVP."],
    ),
  },
  {
    slug: "your-qr-admission-pass",
    title: "Your Admission QR",
    summary: "This QR is what you show at the entrance — keep this link.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "ADMISSION",
    status: "PUBLISHED",
    sortOrder: 4,
    videoUrl: null,
    storyboardKey: "guest-present-qr",
    synonyms: ["qr pass", "show my qr", "admission pass"],
    relatedSlugs: ["present-qr-at-entrance", "event-day-access"],
    posterUrl: "/guides/posters/qr-pass.svg",
    steps: steps(
      ["Find Your Pass", "Scroll to the QR on this invitation."],
      ["Save a backup", "Screenshot or bookmark the link."],
      ["Brightness up", "Make the code easy to scan."],
      ["Show at the door", "Hold still until staff confirm."],
    ),
  },
  {
    slug: "accept-or-decline",
    title: "Accept or Decline",
    summary: "Choose Accept, Decline, or Maybe in plain words.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "RSVP",
    status: "PUBLISHED",
    sortOrder: 40,
    videoUrl: null,
    synonyms: ["accept invite", "decline invite"],
    relatedSlugs: ["rsvp"],
    posterUrl: "/guides/posters/rsvp.svg",
    steps: steps(
      ["Accept", "Tap Accept if you will attend."],
      ["Decline", "Tap Decline if you cannot come."],
      ["Maybe", "Tap Maybe if you are not sure yet."],
      ["Change later", "Open the same invitation link to update."],
    ),
  },
  {
    slug: "choose-party-size",
    title: "Choose Party Size",
    summary: "How many people this invitation covers — including you.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "GUESTS",
    status: "PUBLISHED",
    sortOrder: 41,
    videoUrl: null,
    synonyms: ["party size", "who can come"],
    relatedSlugs: ["rsvp", "plus-guests"],
    posterUrl: "/guides/posters/group.svg",
    steps: steps(
      ["Find the number", "Near RSVP, see how many seats you have."],
      ["Include yourself", "You count as one of the seats."],
      ["Adjust carefully", "Only confirm people who will really attend."],
      ["Ask before extras", "Message the host if you need more seats."],
    ),
  },
  {
    slug: "plus-guests",
    title: "Plus Guests",
    summary: "Bring only the plus guests your host allowed.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "GUESTS",
    status: "PUBLISHED",
    sortOrder: 42,
    videoUrl: null,
    synonyms: ["plus one"],
    relatedSlugs: ["choose-party-size", "group-invitations-plus-guests"],
    posterUrl: "/guides/posters/group.svg",
    steps: steps(
      ["Check allowance", "See if your invite includes plus guests."],
      ["Name them", "Add the names the form asks for."],
      ["RSVP together", "Confirm the full party in one reply."],
      ["Bring passes", "Make sure each person can show a QR if required."],
    ),
  },
  {
    slug: "present-qr-at-entrance",
    title: "Present QR at Entrance",
    summary: "Show your bright QR code to staff at the door.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "ADMISSION",
    status: "PUBLISHED",
    sortOrder: 43,
    videoUrl: null,
    synonyms: ["show qr", "door scan"],
    relatedSlugs: ["your-qr-admission-pass"],
    posterUrl: "/guides/posters/qr-pass.svg",
    steps: steps(
      ["Open the invite", "Use the same link before you reach the door."],
      ["Find Your Pass", "Scroll to the QR."],
      ["Brightness up", "Make the code easy to scan."],
      ["Hold still", "Wait for staff to confirm."],
    ),
  },
  {
    slug: "partial-group-admission",
    title: "Partial Group Admission",
    summary: "When only some of your party arrives together.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "ADMISSION",
    status: "PUBLISHED",
    sortOrder: 44,
    videoUrl: null,
    synonyms: ["partial admission"],
    relatedSlugs: ["present-qr-at-entrance"],
    posterUrl: "/guides/posters/qr-pass.svg",
    steps: steps(
      ["Arrive with who is ready", "You do not need the whole party at once."],
      ["Scan present guests", "Staff admit the people who are here."],
      ["Late arrivals", "They show their QR when they arrive."],
      ["Ask staff if unsure", "Do not share someone else’s unique pass."],
    ),
  },
  {
    slug: "venue-and-directions",
    title: "Venue & Directions",
    summary: "Find where the event is and how to get there.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "EVENT_GUIDE",
    status: "PUBLISHED",
    sortOrder: 45,
    videoUrl: null,
    synonyms: ["venue", "directions", "location"],
    relatedSlugs: ["open-your-invitation"],
    posterUrl: "/guides/posters/event-guide.svg",
    steps: steps(
      ["Find the venue name", "It appears on the invitation details."],
      ["Open directions", "Tap Directions or the map link."],
      ["Plan travel time", "Leave early for parking or traffic."],
      ["Ask the host if lost", "Use Contact Organizer only if the map fails."],
    ),
  },
  {
    slug: "return-to-invitation",
    title: "Return to Invitation",
    summary: "Open the same invitation link anytime — nothing to install.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "INVITATIONS",
    status: "PUBLISHED",
    sortOrder: 46,
    videoUrl: null,
    synonyms: ["reopen invite"],
    relatedSlugs: ["open-your-invitation"],
    posterUrl: "/guides/posters/invitation.svg",
    steps: steps(
      ["Keep the message", "Do not delete the WhatsApp, SMS, or email."],
      ["Tap the link again", "It opens the same invitation."],
      ["Bookmark on your phone", "Add to Home Screen if your phone allows."],
      ["Need a resend?", "Ask the host to send the link again."],
    ),
  },
  {
    slug: "upload-photos",
    title: "Upload Photos",
    summary: "Add photos to the shared Memory Vault album.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "MEMORY",
    status: "PUBLISHED",
    sortOrder: 47,
    videoUrl: null,
    synonyms: ["add photos"],
    relatedSlugs: ["memory-vault-guest"],
    posterUrl: "/guides/posters/memory.svg",
    steps: steps(
      ["Open Memory Vault", "Find Share photos on the invitation."],
      ["Choose photos", "Pick clear pictures from your phone."],
      ["Upload", "Wait until you see success."],
      ["Done", "View the album when you want."],
    ),
  },
  {
    slug: "upload-videos",
    title: "Upload Videos",
    summary: "Share short videos in Memory Vault when the host allows it.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "MEMORY",
    status: "PUBLISHED",
    sortOrder: 48,
    videoUrl: null,
    synonyms: ["share video"],
    relatedSlugs: ["upload-photos"],
    posterUrl: "/guides/posters/memory.svg",
    steps: steps(
      ["Use Wi‑Fi if you can", "Videos are larger than photos."],
      ["Pick a short clip", "Shorter uploads finish more reliably."],
      ["Upload and wait", "Keep the screen on until it finishes."],
      ["Retry if needed", "See Troubleshooting if upload fails."],
    ),
  },
  {
    slug: "view-shared-memories",
    title: "View Shared Memories",
    summary: "Browse photos and videos others shared for this event.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "MEMORY",
    status: "PUBLISHED",
    sortOrder: 49,
    videoUrl: null,
    synonyms: ["view album"],
    relatedSlugs: ["memory-vault-guest"],
    posterUrl: "/guides/posters/memory.svg",
    steps: steps(
      ["Open the album", "Use View album on the invitation."],
      ["Browse kindly", "Respect private moments."],
      ["Add your own", "Upload if the host enabled contributions."],
      ["Return later", "The same link works after the event."],
    ),
  },
  {
    slug: "guest-troubleshooting",
    title: "Troubleshooting",
    summary: "Simple fixes when something on your invitation does not work.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 50,
    featured: true,
    videoUrl: null,
    synonyms: ["help", "not working"],
    relatedSlugs: ["troubleshoot-invitation-wont-open", "troubleshoot-cannot-rsvp", "troubleshoot-qr-not-scanning", "troubleshoot-contact-organizer"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Name the problem", "Invitation, RSVP, QR, seating, guide, or memory."],
      ["Try the recovery steps", "Follow the short checklist for that issue."],
      ["Retry on another network", "Switch to Wi‑Fi or mobile data."],
      ["Contact the host", "Only if you still cannot continue."],
    ),
  },
  {
    slug: "troubleshoot-invitation-wont-open",
    title: "My invitation will not open",
    summary: "Recover when the invitation link fails to load.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 51,
    videoUrl: null,
    synonyms: ["link broken"],
    relatedSlugs: ["open-your-invitation"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Check the link", "Tap the full link from the original message."],
      ["Try another browser", "Open in Safari or Chrome if an in-app browser fails."],
      ["Check internet", "Load any other website to confirm you are online."],
      ["Ask for a resend", "Message the host if the link still fails."],
    ),
  },
  {
    slug: "troubleshoot-cannot-hear-intro",
    title: "I cannot hear the intro",
    summary: "Sound is optional — continue with sound off.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 52,
    videoUrl: null,
    synonyms: ["no sound"],
    relatedSlugs: ["open-your-invitation"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Unmute if you want sound", "Look for a speaker or Unmute control."],
      ["Check phone silent mode", "Raise volume after unmuting."],
      ["Continue without sound", "You can read everything with sound off."],
      ["Skip intro if offered", "Repeat guests may skip the opening."],
    ),
  },
  {
    slug: "troubleshoot-cannot-rsvp",
    title: "I cannot RSVP",
    summary: "Fix a stuck or rejected RSVP form.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 53,
    videoUrl: null,
    synonyms: ["rsvp failed"],
    relatedSlugs: ["rsvp"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Enter your name", "Name is required if the form asks for it."],
      ["Stay on the page", "Wait for the thank-you message after tapping."],
      ["Retry once", "Refresh and try again on a stronger network."],
      ["Contact the host", "Tell them your name and preferred reply."],
    ),
  },
  {
    slug: "troubleshoot-wrong-rsvp",
    title: "I chose the wrong RSVP",
    summary: "Change Accept, Decline, or Maybe from the same link.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 54,
    videoUrl: null,
    synonyms: ["change rsvp"],
    relatedSlugs: ["rsvp"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Reopen the invitation", "Use the same link."],
      ["Find RSVP again", "Scroll to the reply section."],
      ["Choose the correct reply", "Accept, Decline, or Maybe."],
      ["Confirm it saved", "Look for the thank-you confirmation."],
    ),
  },
  {
    slug: "troubleshoot-cannot-find-qr",
    title: "I cannot find my QR",
    summary: "Locate Your Pass on the invitation.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 55,
    videoUrl: null,
    synonyms: ["missing qr"],
    relatedSlugs: ["your-qr-admission-pass"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Scroll to Your Pass", "It is on the same invitation page."],
      ["RSVP first if asked", "Some hosts show the QR after you reply."],
      ["Try Show My QR in help", "Use guest quick actions if available."],
      ["Ask the host", "Request a resend of your personal link."],
    ),
  },
  {
    slug: "troubleshoot-qr-not-scanning",
    title: "My QR is not scanning",
    summary: "Make the code easy for staff scanners to read.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 56,
    videoUrl: null,
    synonyms: ["scan failed"],
    relatedSlugs: ["present-qr-at-entrance"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Brightness up", "Turn the screen as bright as it goes."],
      ["Clean the screen", "Wipe fingerprints over the code."],
      ["Enlarge the QR", "Tap to fullscreen if the pass allows it."],
      ["Use the manual code", "Read the backup code to staff if shown."],
    ),
  },
  {
    slug: "troubleshoot-name-not-in-seating",
    title: "My name is not showing in seating",
    summary: "What to do when search cannot find you.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 57,
    videoUrl: null,
    synonyms: ["name not found"],
    relatedSlugs: ["find-your-seat"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Try fewer letters", "Search part of your first or last name."],
      ["Check spelling", "Use the name on your invitation."],
      ["Wait if early", "Hosts may still be publishing seats."],
      ["Ask the host or usher", "They can place you without guessing."],
    ),
  },
  {
    slug: "troubleshoot-dont-know-table",
    title: "I do not know my table",
    summary: "Find your table using seating search or an usher.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 58,
    videoUrl: null,
    synonyms: ["which table"],
    relatedSlugs: ["find-your-seat"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Open Find my seat", "From the invitation or Event Guide."],
      ["Search your name", "Note the table number."],
      ["Ask an usher", "Show them your name on the phone."],
      ["Do not take another seat", "Wait for guidance if unsure."],
    ),
  },
  {
    slug: "troubleshoot-event-guide-wont-open",
    title: "My Event Guide will not open",
    summary: "Recover when the day-of guide link fails.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 59,
    videoUrl: null,
    synonyms: ["guide broken"],
    relatedSlugs: ["event-guide-guest"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Use the host’s guide link", "Open it from the invitation or message."],
      ["Try another browser", "Leave in-app browsers if they fail."],
      ["Check internet", "Switch between Wi‑Fi and mobile data."],
      ["Ask staff", "They can share the guide QR again."],
    ),
  },
  {
    slug: "troubleshoot-weak-internet",
    title: "I have weak internet",
    summary: "Keep using your invitation with offline-friendly tips.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 60,
    videoUrl: null,
    synonyms: ["slow network"],
    relatedSlugs: ["your-qr-admission-pass"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Load your pass early", "Open Your Pass before you lose signal."],
      ["Screenshot the QR", "Keep a backup image on your phone."],
      ["Switch networks", "Try Wi‑Fi or mobile data."],
      ["Upload memories later", "Photos can wait until you have signal."],
    ),
  },
  {
    slug: "troubleshoot-memory-wont-upload",
    title: "My memory will not upload",
    summary: "Fix failed photo or video uploads.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 61,
    videoUrl: null,
    synonyms: ["upload failed"],
    relatedSlugs: ["upload-photos"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Use Wi‑Fi", "Especially for videos."],
      ["Try a smaller photo", "Or a shorter clip."],
      ["Keep the screen on", "Do not leave the page mid-upload."],
      ["Retry later", "The album link will still work after the event."],
    ),
  },
  {
    slug: "troubleshoot-contact-organizer",
    title: "I need to contact the organizer",
    summary: "Reach the host only when self-serve steps are not enough.",
    body: 'VIDEO PRODUCTION REQUIRED — ship motion/storyboard steps until a real MP4 exists.',
    role: "GUEST",
    category: "TROUBLESHOOTING",
    status: "PUBLISHED",
    sortOrder: 62,
    videoUrl: null,
    synonyms: ["call host"],
    relatedSlugs: ["guest-troubleshooting"],
    posterUrl: "/guides/posters/welcome.svg",
    steps: steps(
      ["Use Contact on the invite", "Call, WhatsApp, or Email if shown."],
      ["Say your full name", "Hosts match you on the guest list."],
      ["State the problem clearly", "RSVP, QR, seating, or guide."],
      ["Include the event name", "So the right host can help quickly."],
    ),
  },
];
