/**
 * Adaptive FFmpeg video transcoding engine — server-only. Never import this from client code.
 *
 * Default path is the TypeScript `ffprobe` + `ffmpeg` pipeline with runtime capability detection
 * (`ffmpeg-capabilities.ts`): HDR→SDR tonemap only when `zscale`+`tonemap` are registered, plain
 * scale/format otherwise, with a one-shot runtime retry if the HDR graph fails unexpectedly.
 *
 * An optional Hostinger VPS binary (`/usr/local/bin/celeventic-process-video`) may hard-require
 * `zscale` with no fallback. Because that binary's presence alone previously short-circuited the
 * adaptive path on production, it is now **opt-in** via `VIDEO_USE_EXTERNAL_CONVERTER=true`.
 * When enabled, any failure (including zscale filter missing, non-zero exit, empty/partial
 * output) clears partial artifacts and always falls through to adaptive ffmpeg — never treated
 * as success.
 *
 * Output contract (always, regardless of which path ran):
 *   - MP4 container, H.264 (yuv420p, "main" profile), AAC audio (or muted if the source has
 *     no audio track), `+faststart` (moov at the front for instant playback / byte-range).
 *   - Max 1080p on the longest dimension, NEVER upscaled past the source resolution.
 *   - Correct orientation (phone-recorded portrait/landscape rotation baked into pixels).
 *   - HDR/Dolby Vision sources are tone-mapped down to SDR BT.709 when the running ffmpeg build
 *     supports `zscale`+`tonemap` (see `ffmpeg-capabilities.ts`). When those filters are
 *     unavailable (e.g. Homebrew macOS ffmpeg without `libzimg`) — or the tonemap pipeline fails
 *     unexpectedly at runtime — we automatically fall back to a plain scale/format pipeline. The
 *     HDR source still ships (readable everywhere, just not tone-mapped) instead of failing the
 *     whole upload solely because an optional filter is missing.
 *   - A JPEG poster frame is produced alongside the video.
 *
 * Safety:
 *   - Every child process is invoked via `execFile` with an argument array — never a shell
 *     string — so there is no command-injection surface even with adversarial filenames.
 *   - All filesystem paths used for processing are generated by this module (via `mkdtemp`
 *     + fixed literal filenames); caller-supplied filenames are NEVER interpolated into a
 *     path, eliminating path traversal.
 *   - Every spawned process has a hard timeout (`VIDEO_PROCESSOR_TIMEOUT_MS`, default 15
 *     minutes) after which it is killed.
 *   - Temp directories are always cleaned up (success, failure, or timeout) via `finally`.
 *   - A process-wide semaphore (`VIDEO_PROCESSOR_CONCURRENCY`, default 1) bounds how many
 *     transcodes run at once — required for a single VPS box with finite CPU. Default of 1
 *     is intentional: this is the documented v1 concurrency limitation (see project report).
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, readFile, rm, writeFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { getFfmpegFullCapabilities, type FfmpegCapabilities, type FfmpegFullCapabilities } from "@/lib/video/ffmpeg-capabilities";

const execFileAsync = promisify(execFile);

// ─── Configuration ──────────────────────────────────────────────────────────

export function getExternalConverterPath(): string {
  return (
    process.env.CELEVENTIC_VIDEO_CONVERTER_PATH?.trim() ||
    // Generic alias — some ops docs/scripts refer to this env var name; both point at the
    // same production binary, first non-empty wins.
    process.env.VIDEO_PROCESSOR_PATH?.trim() ||
    "/usr/local/bin/celeventic-process-video"
  );
}

function getFfmpegBin(): string {
  return process.env.FFMPEG_PATH?.trim() || "ffmpeg";
}

function getFfprobeBin(): string {
  return process.env.FFPROBE_PATH?.trim() || "ffprobe";
}

export const MAX_OUTPUT_WIDTH = 1920;
export const MAX_OUTPUT_HEIGHT = 1080;

function getTimeoutMs(): number {
  const raw = Number(process.env.VIDEO_PROCESSOR_TIMEOUT_MS);
  return Number.isFinite(raw) && raw > 0 ? raw : 15 * 60 * 1000;
}

function getConcurrency(): number {
  const raw = Number(process.env.VIDEO_PROCESSOR_CONCURRENCY);
  return Number.isFinite(raw) && raw >= 1 ? Math.floor(raw) : 1;
}

/** Best-effort existence check for the VPS converter binary — cheap, safe to call per-request. */
export function hasExternalConverter(): boolean {
  try {
    return existsSync(getExternalConverterPath());
  } catch {
    return false;
  }
}

/**
 * Opt-in gate for the Hostinger VPS converter binary. Default is **off** so production always
 * uses the adaptive TypeScript FFmpeg path (capability detection + HDR fallback) even when
 * `/usr/local/bin/celeventic-process-video` exists on disk. Set `VIDEO_USE_EXTERNAL_CONVERTER`
 * to `true` / `1` / `yes` only after verifying that binary's filter graph matches this host's
 * ffmpeg build (notably: never hard-require `zscale` without a fallback).
 */
export function isExternalConverterOptedIn(): boolean {
  const raw = process.env.VIDEO_USE_EXTERNAL_CONVERTER?.trim().toLowerCase();
  return raw === "true" || raw === "1" || raw === "yes";
}

/** True only when the operator explicitly opted in *and* the binary is present on disk. */
export function shouldAttemptExternalConverter(): boolean {
  return isExternalConverterOptedIn() && hasExternalConverter();
}

export class VideoProcessingError extends Error {
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = "VideoProcessingError";
  }
}

// ─── Concurrency limiter ────────────────────────────────────────────────────

/**
 * Minimal async semaphore — no external dependency needed. Bounds how many ffmpeg/converter
 * processes run at once across the whole Node process (single VPS instance).
 */
export class Semaphore {
  private active = 0;
  private readonly queue: Array<() => void> = [];

  constructor(private readonly max: number) {}

  get activeCount(): number {
    return this.active;
  }

  get queueLength(): number {
    return this.queue.length;
  }

  async acquire(): Promise<() => void> {
    if (this.active < this.max) {
      this.active++;
      return () => this.release();
    }
    return new Promise((resolve) => {
      this.queue.push(() => {
        this.active++;
        resolve(() => this.release());
      });
    });
  }

  private release() {
    this.active--;
    const next = this.queue.shift();
    if (next) next();
  }
}

let sharedSemaphore: Semaphore | null = null;
let sharedSemaphoreMax = -1;

/** Lazily (re)created if `VIDEO_PROCESSOR_CONCURRENCY` changes between calls (mainly for tests). */
export function getVideoProcessingSemaphore(): Semaphore {
  const max = getConcurrency();
  if (!sharedSemaphore || sharedSemaphoreMax !== max) {
    sharedSemaphore = new Semaphore(max);
    sharedSemaphoreMax = max;
  }
  return sharedSemaphore;
}

// ─── Process execution ──────────────────────────────────────────────────────

interface RunResult {
  stdout: string;
  stderr: string;
}

async function runProcess(bin: string, args: string[], timeoutMs: number): Promise<RunResult> {
  try {
    const { stdout, stderr } = await execFileAsync(bin, args, {
      timeout: timeoutMs,
      killSignal: "SIGKILL",
      maxBuffer: 64 * 1024 * 1024,
      windowsHide: true,
    });
    return { stdout: stdout.toString(), stderr: stderr.toString() };
  } catch (error) {
    const err = error as NodeJS.ErrnoException & { stdout?: string; stderr?: string; killed?: boolean; signal?: string };
    if (err.killed || err.signal === "SIGKILL" || err.signal === "SIGTERM") {
      throw new VideoProcessingError(`${bin} timed out after ${timeoutMs}ms and was killed.`, error);
    }
    if (err.code === "ENOENT") {
      throw new VideoProcessingError(`${bin} is not installed or not on PATH.`, error);
    }
    const stderrTail = (err.stderr ?? "").toString().slice(-2000);
    throw new VideoProcessingError(`${bin} failed: ${err.message}${stderrTail ? `\n${stderrTail}` : ""}`, error);
  }
}

// ─── ffprobe metadata ───────────────────────────────────────────────────────

export interface ProbeResult {
  durationSeconds: number | null;
  width: number | null;
  height: number | null;
  /** Rotation baked into the container's display matrix / rotate tag, normalized to 0/90/180/270. */
  rotation: number;
  videoCodec: string | null;
  audioCodec: string | null;
  hasAudio: boolean;
  isHevc: boolean;
  isHdr: boolean;
  colorTransfer: string | null;
  colorPrimaries: string | null;
}

interface FfprobeStream {
  codec_type?: string;
  codec_name?: string;
  width?: number;
  height?: number;
  color_transfer?: string;
  color_primaries?: string;
  tags?: Record<string, string>;
  side_data_list?: Array<Record<string, unknown>>;
}

interface FfprobeOutput {
  streams?: FfprobeStream[];
  format?: { duration?: string };
}

const HEVC_NAMES = new Set(["hevc", "h265"]);
const HDR_TRANSFERS = new Set(["smpte2084", "arib-std-b67"]);

/** Pure — testable without spawning ffprobe. Parses the JSON ffprobe already produced. */
export function parseFfprobeJson(raw: string): ProbeResult {
  const empty: ProbeResult = {
    durationSeconds: null,
    width: null,
    height: null,
    rotation: 0,
    videoCodec: null,
    audioCodec: null,
    hasAudio: false,
    isHevc: false,
    isHdr: false,
    colorTransfer: null,
    colorPrimaries: null,
  };

  let json: FfprobeOutput;
  try {
    json = JSON.parse(raw);
  } catch {
    return empty;
  }

  const streams = json.streams ?? [];
  const videoStream = streams.find((s) => s.codec_type === "video");
  const audioStream = streams.find((s) => s.codec_type === "audio");

  const durationSeconds = json.format?.duration ? Number(json.format.duration) : null;

  let rotation = 0;
  if (videoStream) {
    const tagRotate = videoStream.tags?.rotate;
    if (tagRotate) rotation = normalizeRotation(Number(tagRotate));
    const sideData = videoStream.side_data_list?.find((sd) => typeof sd.rotation === "number");
    if (sideData && typeof sideData.rotation === "number") {
      // Display-matrix rotation is signed and can be e.g. -90; normalize to 0/90/180/270.
      rotation = normalizeRotation(-(sideData.rotation as number));
    }
  }

  const codecName = videoStream?.codec_name?.toLowerCase() ?? null;
  const colorTransfer = videoStream?.color_transfer?.toLowerCase() ?? null;
  const colorPrimaries = videoStream?.color_primaries?.toLowerCase() ?? null;

  return {
    durationSeconds: Number.isFinite(durationSeconds) ? durationSeconds : null,
    width: videoStream?.width ?? null,
    height: videoStream?.height ?? null,
    rotation,
    videoCodec: codecName,
    audioCodec: audioStream?.codec_name?.toLowerCase() ?? null,
    hasAudio: Boolean(audioStream),
    isHevc: codecName ? HEVC_NAMES.has(codecName) : false,
    isHdr: Boolean(colorTransfer && HDR_TRANSFERS.has(colorTransfer)) || colorPrimaries === "bt2020",
    colorTransfer,
    colorPrimaries,
  };
}

function normalizeRotation(deg: number): number {
  const n = ((Math.round(deg / 90) * 90) % 360 + 360) % 360;
  return n;
}

export async function probeVideoFile(inputPath: string): Promise<ProbeResult> {
  const args = [
    "-v", "error",
    "-print_format", "json",
    "-show_format",
    "-show_streams",
    inputPath,
  ];
  const { stdout } = await runProcess(getFfprobeBin(), args, 60_000);
  return parseFfprobeJson(stdout);
}

// ─── ffmpeg filter/argument construction (pure, testable) ─────────────────

/** True when the source is already safe to ship as-is (no re-encode needed — just a faststart remux). */
export function isAlreadyBrowserCompatible(probe: ProbeResult): boolean {
  if (!probe.videoCodec || probe.videoCodec !== "h264") return false;
  if (probe.isHdr) return false;
  if (probe.rotation !== 0) return false;
  if (probe.audioCodec && probe.audioCodec !== "aac") return false;
  if (probe.width && probe.width > MAX_OUTPUT_WIDTH) return false;
  if (probe.height && probe.height > MAX_OUTPUT_HEIGHT) return false;
  return true;
}

/**
 * Default capabilities assumed when the caller doesn't pass any — i.e. "the zscale/tonemap HDR
 * pipeline is available". Callers that actually care whether it's safe to use it (the real
 * transcode orchestration below) must probe via `ffmpeg-capabilities.ts` and pass the result in.
 */
const ASSUME_HDR_CAPABLE: FfmpegCapabilities = { hasZscale: true, hasTonemap: true };

/**
 * Builds the `-vf` filter chain: scale to <=1080p (never upscale) + orientation + yuv420p, and
 * — only when the source is HDR *and* the running ffmpeg registers both `zscale` and `tonemap`
 * (see `ffmpeg-capabilities.ts`) — an HDR->SDR BT.709 tonemap stage. When either filter is
 * missing, we silently use the plain scale/format chain instead of throwing: the HDR source
 * still ships (correct, just not tone-mapped) rather than failing the whole upload over an
 * optional filter some ffmpeg builds (e.g. Homebrew macOS without `libzimg`) don't ship.
 */
export function buildVideoFilterChain(probe: ProbeResult, caps: FfmpegCapabilities = ASSUME_HDR_CAPABLE): string {
  const scale = `scale='min(${MAX_OUTPUT_WIDTH},iw)':'min(${MAX_OUTPUT_HEIGHT},ih)':force_original_aspect_ratio=decrease:force_divisible_by=2`;
  if (probe.isHdr && caps.hasZscale && caps.hasTonemap) {
    // Tone-map HDR (PQ/HLG, e.g. Dolby Vision/HDR10 iPhone footage) down to SDR BT.709.
    return [
      scale,
      "zscale=t=linear:npl=100",
      "format=gbrpf32le",
      "zscale=p=bt709",
      "tonemap=tonemap=hable:desat=0",
      "zscale=t=bt709:m=bt709:r=tv",
      "format=yuv420p",
    ].join(",");
  }
  return `${scale},format=yuv420p`;
}

export function buildTranscodeArgs(
  inputPath: string,
  outputPath: string,
  probe: ProbeResult,
  caps: FfmpegCapabilities = ASSUME_HDR_CAPABLE
): string[] {
  // `-autorotate` is a boolean CLI flag — some ffmpeg builds (7.x+) parse a bare trailing value
  // like `-autorotate 1` as a *separate* positional output argument (not the flag's value),
  // which corrupts the whole command line ("Error parsing options for output file 1"). Passing
  // the flag with no value enables it (the documented default anyway) and works identically
  // across ffmpeg versions that support the option at all.
  const args: string[] = ["-y", "-autorotate", "-i", inputPath];
  args.push("-map", "0:v:0");
  if (probe.hasAudio) args.push("-map", "0:a:0?");
  args.push("-vf", buildVideoFilterChain(probe, caps));
  args.push(
    "-c:v", "libx264",
    "-profile:v", "main",
    "-level", "4.0",
    "-preset", "veryfast",
    "-crf", "21",
    "-pix_fmt", "yuv420p",
    "-movflags", "+faststart"
  );
  if (probe.hasAudio) {
    args.push("-c:a", "aac", "-b:a", "128k", "-ac", "2", "-ar", "48000");
  } else {
    args.push("-an");
  }
  args.push("-max_muxing_queue_size", "1024", outputPath);
  return args;
}

export function buildRemuxArgs(inputPath: string, outputPath: string): string[] {
  // Already H.264/AAC/yuv420p/<=1080p/no-rotation — just relocate `moov` for fast-start / byte-range.
  return ["-y", "-i", inputPath, "-c", "copy", "-movflags", "+faststart", outputPath];
}

export function buildPosterArgs(inputPath: string, outputPath: string, seekSeconds: number): string[] {
  return [
    "-y",
    "-ss", seekSeconds.toFixed(2),
    "-i", inputPath,
    "-frames:v", "1",
    "-vf", "scale='min(1280,iw)':-2:force_divisible_by=2",
    "-q:v", "3",
    outputPath,
  ];
}

/** Safe, sub-second-tolerant poster timestamp: ~10% into the clip, capped, never past the end. */
export function choosePosterSeekSeconds(durationSeconds: number | null): number {
  if (!durationSeconds || durationSeconds <= 0) return 0;
  return Math.min(3, Math.max(0, durationSeconds * 0.1));
}

/**
 * Only HDR sources need to know about zscale/tonemap availability at all — probing costs nothing
 * extra after the first call (cached in `ffmpeg-capabilities.ts`), but SDR sources skip it
 * entirely since the result would never change which filter chain they get.
 */
async function resolveHdrCapabilities(probe: ProbeResult): Promise<FfmpegCapabilities> {
  if (!probe.isHdr) return { hasZscale: false, hasTonemap: false };
  const [hasZscale, hasTonemap] = await Promise.all([supportsFilter("zscale"), supportsFilter("tonemap")]);
  return { hasZscale, hasTonemap };
}

/**
 * Runs the real transcode, choosing the HDR zscale/tonemap pipeline only when both filters are
 * confirmed available; otherwise (or for SDR sources) uses the plain scale/format fallback. If
 * the zscale/tonemap pipeline is attempted but fails unexpectedly at runtime (e.g. a build with a
 * broken/partial `libzimg`), automatically retries once with the fallback pipeline instead of
 * failing the whole upload — an HDR source that ships un-tone-mapped beats one that doesn't ship
 * at all.
 */
async function transcodeWithHdrFallback(
  inputPath: string,
  outputPath: string,
  probe: ProbeResult,
  timeoutMs: number
): Promise<void> {
  const caps = await resolveHdrCapabilities(probe);
  const attemptingHdrPipeline = probe.isHdr && caps.hasZscale && caps.hasTonemap;
  try {
    await runProcess(getFfmpegBin(), buildTranscodeArgs(inputPath, outputPath, probe, caps), timeoutMs);
  } catch (error) {
    if (!attemptingHdrPipeline) throw error; // already ran the safe fallback — nothing left to retry
    const fallbackCaps: FfmpegCapabilities = { hasZscale: false, hasTonemap: false };
    await runProcess(getFfmpegBin(), buildTranscodeArgs(inputPath, outputPath, probe, fallbackCaps), timeoutMs);
  }
}

// ─── Orchestration ──────────────────────────────────────────────────────────

export interface ProcessedVideoMetadata {
  durationSeconds: number | null;
  width: number | null;
  height: number | null;
  hadHevc: boolean;
  hadHdr: boolean;
  hasAudio: boolean;
}

export interface ProcessVideoResult {
  success: boolean;
  method: "external-converter" | "ffmpeg-transcode" | "ffmpeg-remux" | "none";
  outputBuffer: Buffer | null;
  posterBuffer: Buffer | null;
  metadata: ProcessedVideoMetadata;
  error?: string;
}

const EMPTY_METADATA: ProcessedVideoMetadata = {
  durationSeconds: null,
  width: null,
  height: null,
  hadHevc: false,
  hadHdr: false,
  hasAudio: false,
};

/** Extension hint only — never trusted for anything security-sensitive (ffmpeg content-sniffs the demuxer). */
function guessExtension(sourceExtHint: string | null | undefined): string {
  const clean = (sourceExtHint ?? "").replace(/[^a-z0-9]/gi, "").toLowerCase();
  return clean || "bin";
}

/**
 * Runs adaptive ffprobe+ffmpeg by default. Optionally tries the VPS converter binary first
 * when `VIDEO_USE_EXTERNAL_CONVERTER` is explicitly enabled — any external failure (including
 * zscale missing, empty/partial output) clears artifacts and falls through to adaptive ffmpeg.
 * Always produces an MP4 (H.264/AAC/yuv420p/faststart, <=1080p, corrected orientation, SDR) +
 * JPEG poster, or fails with a clear reason — never silently returns an unplayable/HEVC file.
 *
 * `inputBuffer` is written to an isolated temp dir this function fully owns and cleans up;
 * the caller never needs to manage filesystem paths.
 */
export async function processVideoFile(
  inputBuffer: Buffer,
  options: { extensionHint?: string | null; timeoutMs?: number } = {}
): Promise<ProcessVideoResult> {
  const timeoutMs = options.timeoutMs ?? getTimeoutMs();
  const workDir = await mkdtemp(path.join(os.tmpdir(), "celeventic-video-"));
  const inputPath = path.join(workDir, `input.${guessExtension(options.extensionHint)}`);
  const outputPath = path.join(workDir, "output.mp4");
  const posterPath = path.join(workDir, "poster.jpg");

  const release = await getVideoProcessingSemaphore().acquire();
  try {
    await writeFile(inputPath, inputBuffer);

    // 1) Optional external converter — OFF by default. Presence of the Hostinger binary alone
    // must never short-circuit the adaptive TS path (that binary may hard-require zscale).
    if (shouldAttemptExternalConverter()) {
      try {
        await runProcess(
          getExternalConverterPath(),
          ["--input", inputPath, "--output", outputPath, "--poster", posterPath, "--max-width", String(MAX_OUTPUT_WIDTH), "--max-height", String(MAX_OUTPUT_HEIGHT)],
          timeoutMs
        );
        if (await fileNonEmpty(outputPath)) {
          const metadata = await deriveMetadata(inputPath, outputPath);
          return {
            success: true,
            method: "external-converter",
            outputBuffer: await readFile(outputPath),
            posterBuffer: (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : await extractPosterFallback(outputPath, posterPath, metadata.durationSeconds),
            metadata,
          };
        }
        // Converter exited 0 but left empty/missing output — not success. Clear and fall through.
        await clearPartialOutputs(outputPath, posterPath);
      } catch {
        // Any error (zscale missing, wrong CLI, timeout, non-zero exit) — clear partial
        // artifacts so we never treat a failed external convert as success, then fall through
        // to adaptive ffmpeg below.
        await clearPartialOutputs(outputPath, posterPath);
      }
    }

    // 2) Adaptive ffprobe + ffmpeg (default path; also the fallthrough after external failure).
    const inputProbe = await probeVideoFile(inputPath).catch(() => null);
    const remuxEligible = inputProbe ? isAlreadyBrowserCompatible(inputProbe) : false;

    if (remuxEligible && inputProbe) {
      try {
        await runProcess(getFfmpegBin(), buildRemuxArgs(inputPath, outputPath), timeoutMs);
        const posterSeek = choosePosterSeekSeconds(inputProbe.durationSeconds);
        await runProcess(getFfmpegBin(), buildPosterArgs(outputPath, posterPath, posterSeek), Math.min(timeoutMs, 60_000));
        return {
          success: true,
          method: "ffmpeg-remux",
          outputBuffer: await readFile(outputPath),
          posterBuffer: (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : null,
          metadata: metadataFromProbe(inputProbe),
        };
      } catch {
        // Remux failed (e.g. unusual edit lists) — clear partials and fall back to full transcode.
        await clearPartialOutputs(outputPath, posterPath);
      }
    }

    const probe = inputProbe ?? (await probeVideoFile(inputPath));
    await transcodeWithHdrFallback(inputPath, outputPath, probe, timeoutMs);
    const posterSeek = choosePosterSeekSeconds(probe.durationSeconds);
    await runProcess(getFfmpegBin(), buildPosterArgs(outputPath, posterPath, posterSeek), Math.min(timeoutMs, 60_000));

    return {
      success: true,
      method: "ffmpeg-transcode",
      outputBuffer: await readFile(outputPath),
      posterBuffer: (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : null,
      metadata: metadataFromProbe(probe),
    };
  } catch (error) {
    return {
      success: false,
      method: "none",
      outputBuffer: null,
      posterBuffer: null,
      metadata: EMPTY_METADATA,
      error: error instanceof Error ? error.message : "Video processing failed.",
    };
  } finally {
    release();
    await rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

/** Remove leftover output/poster files so a failed path cannot be mistaken for success later. */
async function clearPartialOutputs(...paths: string[]): Promise<void> {
  await Promise.all(paths.map((p) => rm(p, { force: true }).catch(() => {})));
}

async function fileNonEmpty(p: string): Promise<boolean> {
  try {
    const s = await stat(p);
    return s.size > 0;
  } catch {
    return false;
  }
}

function metadataFromProbe(probe: ProbeResult): ProcessedVideoMetadata {
  return {
    durationSeconds: probe.durationSeconds,
    width: probe.rotation === 90 || probe.rotation === 270 ? probe.height : probe.width,
    height: probe.rotation === 90 || probe.rotation === 270 ? probe.width : probe.height,
    hadHevc: probe.isHevc,
    hadHdr: probe.isHdr,
    hasAudio: probe.hasAudio,
  };
}

/** Metadata for the external-converter path: probe the *input* for hadHevc/hadHdr flags, the *output* for final dimensions/duration. */
async function deriveMetadata(inputPath: string, outputPath: string): Promise<ProcessedVideoMetadata> {
  const [inputProbe, outputProbe] = await Promise.all([
    probeVideoFile(inputPath).catch(() => null),
    probeVideoFile(outputPath).catch(() => null),
  ]);
  return {
    durationSeconds: outputProbe?.durationSeconds ?? inputProbe?.durationSeconds ?? null,
    width: outputProbe?.width ?? null,
    height: outputProbe?.height ?? null,
    hadHevc: inputProbe?.isHevc ?? false,
    hadHdr: inputProbe?.isHdr ?? false,
    hasAudio: outputProbe?.hasAudio ?? inputProbe?.hasAudio ?? false,
  };
}

/** If the external converter didn't produce its own poster, grab one from our ffmpeg as a safety net. */
async function extractPosterFallback(outputPath: string, posterPath: string, durationSeconds: number | null): Promise<Buffer | null> {
  try {
    await runProcess(getFfmpegBin(), buildPosterArgs(outputPath, posterPath, choosePosterSeekSeconds(durationSeconds)), 60_000);
    return (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : null;
  } catch {
    return null;
  }
}

/**
 * Derives a small grid/list thumbnail from the (larger) poster frame — distinct asset from the
 * poster so cards/lists can ship a lighter payload than the detail-view poster. Uses `sharp`
 * (already a project dependency, image-only, no ffmpeg spawn needed) so it's cheap and safe to
 * run on every upload/backfill item. Best-effort: returns `null` (never throws) if `sharp` is
 * unavailable or the poster buffer isn't decodable — callers should fall back to the poster URL.
 */
export async function generateThumbnail(posterBuffer: Buffer, maxWidth = 480): Promise<Buffer | null> {
  try {
    const sharp = (await import("sharp")).default;
    return await sharp(posterBuffer)
      .resize({ width: maxWidth, withoutEnlargement: true })
      .jpeg({ quality: 70 })
      .toBuffer();
  } catch {
    return null;
  }
}
