/**
 * VPS-first video transcoding engine — server-only. Never import this from client code.
 *
 * Production (Hostinger VPS) already ships a converter binary at
 * `/usr/local/bin/celeventic-process-video`. When present, we shell out to it (it already
 * encapsulates the ffmpeg/ffprobe invocation on that box). When absent (local dev, other
 * hosts, or if the binary fails), we fall back to calling `ffprobe` + `ffmpeg` directly with
 * the exact same output contract, so callers never need to know which path ran.
 *
 * Output contract (always, regardless of which path ran):
 *   - MP4 container, H.264 (yuv420p, "main" profile), AAC audio (or muted if the source has
 *     no audio track), `+faststart` (moov at the front for instant playback / byte-range).
 *   - Max 1080p on the longest dimension, NEVER upscaled past the source resolution.
 *   - Correct orientation (phone-recorded portrait/landscape rotation baked into pixels).
 *   - HDR/Dolby Vision sources are tone-mapped down to SDR BT.709 (best-effort — requires an
 *     ffmpeg build with `zscale`; if unsupported, processing fails loudly rather than
 *     silently shipping an HDR file browsers can't decode).
 *   - A JPEG poster frame is produced alongside the video.
 *
 * Safety:
 *   - Every child process is invoked via `execFile` with an argument array — never a shell
 *     string — so there is no command-injection surface even with adversarial filenames.
 *   - All filesystem paths used for processing are generated by this module (via `mkdtemp`
 *     + fixed literal filenames); caller-supplied filenames are NEVER interpolated into a
 *     path, eliminating path traversal.
 *   - Every spawned process has a hard timeout (`VIDEO_PROCESSOR_TIMEOUT_MS`, default 15
 *     minutes) after which it is killed.
 *   - Temp directories are always cleaned up (success, failure, or timeout) via `finally`.
 *   - A process-wide semaphore (`VIDEO_PROCESSOR_CONCURRENCY`, default 1) bounds how many
 *     transcodes run at once — required for a single VPS box with finite CPU. Default of 1
 *     is intentional: this is the documented v1 concurrency limitation (see project report).
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, readFile, rm, writeFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";

const execFileAsync = promisify(execFile);

// ─── Configuration ──────────────────────────────────────────────────────────

export function getExternalConverterPath(): string {
  return (process.env.CELEVENTIC_VIDEO_CONVERTER_PATH?.trim()) || "/usr/local/bin/celeventic-process-video";
}

function getFfmpegBin(): string {
  return process.env.FFMPEG_PATH?.trim() || "ffmpeg";
}

function getFfprobeBin(): string {
  return process.env.FFPROBE_PATH?.trim() || "ffprobe";
}

export const MAX_OUTPUT_WIDTH = 1920;
export const MAX_OUTPUT_HEIGHT = 1080;

function getTimeoutMs(): number {
  const raw = Number(process.env.VIDEO_PROCESSOR_TIMEOUT_MS);
  return Number.isFinite(raw) && raw > 0 ? raw : 15 * 60 * 1000;
}

function getConcurrency(): number {
  const raw = Number(process.env.VIDEO_PROCESSOR_CONCURRENCY);
  return Number.isFinite(raw) && raw >= 1 ? Math.floor(raw) : 1;
}

/** Best-effort existence check for the VPS converter binary — cheap, safe to call per-request. */
export function hasExternalConverter(): boolean {
  try {
    return existsSync(getExternalConverterPath());
  } catch {
    return false;
  }
}

export class VideoProcessingError extends Error {
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = "VideoProcessingError";
  }
}

// ─── Concurrency limiter ────────────────────────────────────────────────────

/**
 * Minimal async semaphore — no external dependency needed. Bounds how many ffmpeg/converter
 * processes run at once across the whole Node process (single VPS instance).
 */
export class Semaphore {
  private active = 0;
  private readonly queue: Array<() => void> = [];

  constructor(private readonly max: number) {}

  get activeCount(): number {
    return this.active;
  }

  get queueLength(): number {
    return this.queue.length;
  }

  async acquire(): Promise<() => void> {
    if (this.active < this.max) {
      this.active++;
      return () => this.release();
    }
    return new Promise((resolve) => {
      this.queue.push(() => {
        this.active++;
        resolve(() => this.release());
      });
    });
  }

  private release() {
    this.active--;
    const next = this.queue.shift();
    if (next) next();
  }
}

let sharedSemaphore: Semaphore | null = null;
let sharedSemaphoreMax = -1;

/** Lazily (re)created if `VIDEO_PROCESSOR_CONCURRENCY` changes between calls (mainly for tests). */
export function getVideoProcessingSemaphore(): Semaphore {
  const max = getConcurrency();
  if (!sharedSemaphore || sharedSemaphoreMax !== max) {
    sharedSemaphore = new Semaphore(max);
    sharedSemaphoreMax = max;
  }
  return sharedSemaphore;
}

// ─── Process execution ──────────────────────────────────────────────────────

interface RunResult {
  stdout: string;
  stderr: string;
}

async function runProcess(bin: string, args: string[], timeoutMs: number): Promise<RunResult> {
  try {
    const { stdout, stderr } = await execFileAsync(bin, args, {
      timeout: timeoutMs,
      killSignal: "SIGKILL",
      maxBuffer: 64 * 1024 * 1024,
      windowsHide: true,
    });
    return { stdout: stdout.toString(), stderr: stderr.toString() };
  } catch (error) {
    const err = error as NodeJS.ErrnoException & { stdout?: string; stderr?: string; killed?: boolean; signal?: string };
    if (err.killed || err.signal === "SIGKILL" || err.signal === "SIGTERM") {
      throw new VideoProcessingError(`${bin} timed out after ${timeoutMs}ms and was killed.`, error);
    }
    if (err.code === "ENOENT") {
      throw new VideoProcessingError(`${bin} is not installed or not on PATH.`, error);
    }
    const stderrTail = (err.stderr ?? "").toString().slice(-2000);
    throw new VideoProcessingError(`${bin} failed: ${err.message}${stderrTail ? `\n${stderrTail}` : ""}`, error);
  }
}

// ─── ffprobe metadata ───────────────────────────────────────────────────────

export interface ProbeResult {
  durationSeconds: number | null;
  width: number | null;
  height: number | null;
  /** Rotation baked into the container's display matrix / rotate tag, normalized to 0/90/180/270. */
  rotation: number;
  videoCodec: string | null;
  audioCodec: string | null;
  hasAudio: boolean;
  isHevc: boolean;
  isHdr: boolean;
  colorTransfer: string | null;
  colorPrimaries: string | null;
}

interface FfprobeStream {
  codec_type?: string;
  codec_name?: string;
  width?: number;
  height?: number;
  color_transfer?: string;
  color_primaries?: string;
  tags?: Record<string, string>;
  side_data_list?: Array<Record<string, unknown>>;
}

interface FfprobeOutput {
  streams?: FfprobeStream[];
  format?: { duration?: string };
}

const HEVC_NAMES = new Set(["hevc", "h265"]);
const HDR_TRANSFERS = new Set(["smpte2084", "arib-std-b67"]);

/** Pure — testable without spawning ffprobe. Parses the JSON ffprobe already produced. */
export function parseFfprobeJson(raw: string): ProbeResult {
  const empty: ProbeResult = {
    durationSeconds: null,
    width: null,
    height: null,
    rotation: 0,
    videoCodec: null,
    audioCodec: null,
    hasAudio: false,
    isHevc: false,
    isHdr: false,
    colorTransfer: null,
    colorPrimaries: null,
  };

  let json: FfprobeOutput;
  try {
    json = JSON.parse(raw);
  } catch {
    return empty;
  }

  const streams = json.streams ?? [];
  const videoStream = streams.find((s) => s.codec_type === "video");
  const audioStream = streams.find((s) => s.codec_type === "audio");

  const durationSeconds = json.format?.duration ? Number(json.format.duration) : null;

  let rotation = 0;
  if (videoStream) {
    const tagRotate = videoStream.tags?.rotate;
    if (tagRotate) rotation = normalizeRotation(Number(tagRotate));
    const sideData = videoStream.side_data_list?.find((sd) => typeof sd.rotation === "number");
    if (sideData && typeof sideData.rotation === "number") {
      // Display-matrix rotation is signed and can be e.g. -90; normalize to 0/90/180/270.
      rotation = normalizeRotation(-(sideData.rotation as number));
    }
  }

  const codecName = videoStream?.codec_name?.toLowerCase() ?? null;
  const colorTransfer = videoStream?.color_transfer?.toLowerCase() ?? null;
  const colorPrimaries = videoStream?.color_primaries?.toLowerCase() ?? null;

  return {
    durationSeconds: Number.isFinite(durationSeconds) ? durationSeconds : null,
    width: videoStream?.width ?? null,
    height: videoStream?.height ?? null,
    rotation,
    videoCodec: codecName,
    audioCodec: audioStream?.codec_name?.toLowerCase() ?? null,
    hasAudio: Boolean(audioStream),
    isHevc: codecName ? HEVC_NAMES.has(codecName) : false,
    isHdr: Boolean(colorTransfer && HDR_TRANSFERS.has(colorTransfer)) || colorPrimaries === "bt2020",
    colorTransfer,
    colorPrimaries,
  };
}

function normalizeRotation(deg: number): number {
  const n = ((Math.round(deg / 90) * 90) % 360 + 360) % 360;
  return n;
}

export async function probeVideoFile(inputPath: string): Promise<ProbeResult> {
  const args = [
    "-v", "error",
    "-print_format", "json",
    "-show_format",
    "-show_streams",
    inputPath,
  ];
  const { stdout } = await runProcess(getFfprobeBin(), args, 60_000);
  return parseFfprobeJson(stdout);
}

// ─── ffmpeg filter/argument construction (pure, testable) ─────────────────

/** True when the source is already safe to ship as-is (no re-encode needed — just a faststart remux). */
export function isAlreadyBrowserCompatible(probe: ProbeResult): boolean {
  if (!probe.videoCodec || probe.videoCodec !== "h264") return false;
  if (probe.isHdr) return false;
  if (probe.rotation !== 0) return false;
  if (probe.audioCodec && probe.audioCodec !== "aac") return false;
  if (probe.width && probe.width > MAX_OUTPUT_WIDTH) return false;
  if (probe.height && probe.height > MAX_OUTPUT_HEIGHT) return false;
  return true;
}

/** Builds the `-vf` filter chain: scale to <=1080p (never upscale) + orientation + HDR tonemap + yuv420p. */
export function buildVideoFilterChain(probe: ProbeResult): string {
  const scale = `scale='min(${MAX_OUTPUT_WIDTH},iw)':'min(${MAX_OUTPUT_HEIGHT},ih)':force_original_aspect_ratio=decrease:force_divisible_by=2`;
  if (probe.isHdr) {
    // Tone-map HDR (PQ/HLG, e.g. Dolby Vision/HDR10 iPhone footage) down to SDR BT.709.
    return [
      scale,
      "zscale=t=linear:npl=100",
      "format=gbrpf32le",
      "zscale=p=bt709",
      "tonemap=tonemap=hable:desat=0",
      "zscale=t=bt709:m=bt709:r=tv",
      "format=yuv420p",
    ].join(",");
  }
  return `${scale},format=yuv420p`;
}

export function buildTranscodeArgs(inputPath: string, outputPath: string, probe: ProbeResult): string[] {
  const args: string[] = ["-y", "-autorotate", "1", "-i", inputPath];
  args.push("-map", "0:v:0");
  if (probe.hasAudio) args.push("-map", "0:a:0?");
  args.push("-vf", buildVideoFilterChain(probe));
  args.push(
    "-c:v", "libx264",
    "-profile:v", "main",
    "-level", "4.0",
    "-preset", "veryfast",
    "-crf", "21",
    "-pix_fmt", "yuv420p",
    "-movflags", "+faststart"
  );
  if (probe.hasAudio) {
    args.push("-c:a", "aac", "-b:a", "128k", "-ac", "2", "-ar", "48000");
  } else {
    args.push("-an");
  }
  args.push("-max_muxing_queue_size", "1024", outputPath);
  return args;
}

export function buildRemuxArgs(inputPath: string, outputPath: string): string[] {
  // Already H.264/AAC/yuv420p/<=1080p/no-rotation — just relocate `moov` for fast-start / byte-range.
  return ["-y", "-i", inputPath, "-c", "copy", "-movflags", "+faststart", outputPath];
}

export function buildPosterArgs(inputPath: string, outputPath: string, seekSeconds: number): string[] {
  return [
    "-y",
    "-ss", seekSeconds.toFixed(2),
    "-i", inputPath,
    "-frames:v", "1",
    "-vf", "scale='min(1280,iw)':-2:force_divisible_by=2",
    "-q:v", "3",
    outputPath,
  ];
}

/** Safe, sub-second-tolerant poster timestamp: ~10% into the clip, capped, never past the end. */
export function choosePosterSeekSeconds(durationSeconds: number | null): number {
  if (!durationSeconds || durationSeconds <= 0) return 0;
  return Math.min(3, Math.max(0, durationSeconds * 0.1));
}

// ─── Orchestration ──────────────────────────────────────────────────────────

export interface ProcessedVideoMetadata {
  durationSeconds: number | null;
  width: number | null;
  height: number | null;
  hadHevc: boolean;
  hadHdr: boolean;
  hasAudio: boolean;
}

export interface ProcessVideoResult {
  success: boolean;
  method: "external-converter" | "ffmpeg-transcode" | "ffmpeg-remux" | "none";
  outputBuffer: Buffer | null;
  posterBuffer: Buffer | null;
  metadata: ProcessedVideoMetadata;
  error?: string;
}

const EMPTY_METADATA: ProcessedVideoMetadata = {
  durationSeconds: null,
  width: null,
  height: null,
  hadHevc: false,
  hadHdr: false,
  hasAudio: false,
};

/** Extension hint only — never trusted for anything security-sensitive (ffmpeg content-sniffs the demuxer). */
function guessExtension(sourceExtHint: string | null | undefined): string {
  const clean = (sourceExtHint ?? "").replace(/[^a-z0-9]/gi, "").toLowerCase();
  return clean || "bin";
}

/**
 * Runs the VPS converter binary if present, else ffprobe+ffmpeg. Always produces an
 * MP4 (H.264/AAC/yuv420p/faststart, <=1080p, corrected orientation, SDR) + JPEG poster,
 * or fails with a clear reason — never silently returns an unplayable/HEVC file.
 *
 * `inputBuffer` is written to an isolated temp dir this function fully owns and cleans up;
 * the caller never needs to manage filesystem paths.
 */
export async function processVideoFile(
  inputBuffer: Buffer,
  options: { extensionHint?: string | null; timeoutMs?: number } = {}
): Promise<ProcessVideoResult> {
  const timeoutMs = options.timeoutMs ?? getTimeoutMs();
  const workDir = await mkdtemp(path.join(os.tmpdir(), "celeventic-video-"));
  const inputPath = path.join(workDir, `input.${guessExtension(options.extensionHint)}`);
  const outputPath = path.join(workDir, "output.mp4");
  const posterPath = path.join(workDir, "poster.jpg");

  const release = await getVideoProcessingSemaphore().acquire();
  try {
    await writeFile(inputPath, inputBuffer);

    // 1) Prefer the VPS-native converter when present.
    if (hasExternalConverter()) {
      try {
        await runProcess(
          getExternalConverterPath(),
          ["--input", inputPath, "--output", outputPath, "--poster", posterPath, "--max-width", String(MAX_OUTPUT_WIDTH), "--max-height", String(MAX_OUTPUT_HEIGHT)],
          timeoutMs
        );
        if (await fileNonEmpty(outputPath)) {
          const metadata = await deriveMetadata(inputPath, outputPath);
          return {
            success: true,
            method: "external-converter",
            outputBuffer: await readFile(outputPath),
            posterBuffer: (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : await extractPosterFallback(outputPath, posterPath, metadata.durationSeconds),
            metadata,
          };
        }
      } catch {
        // Fall through to the ffmpeg path below — the external converter is a nice-to-have,
        // not a hard dependency. This keeps upload success independent of that binary's
        // exact CLI contract (which may evolve on the VPS without us knowing).
      }
    }

    // 2) ffprobe + ffmpeg fallback (also the only path when no external converter exists).
    const inputProbe = await probeVideoFile(inputPath).catch(() => null);
    const remuxEligible = inputProbe ? isAlreadyBrowserCompatible(inputProbe) : false;

    if (remuxEligible && inputProbe) {
      try {
        await runProcess(getFfmpegBin(), buildRemuxArgs(inputPath, outputPath), timeoutMs);
        const posterSeek = choosePosterSeekSeconds(inputProbe.durationSeconds);
        await runProcess(getFfmpegBin(), buildPosterArgs(outputPath, posterPath, posterSeek), Math.min(timeoutMs, 60_000));
        return {
          success: true,
          method: "ffmpeg-remux",
          outputBuffer: await readFile(outputPath),
          posterBuffer: (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : null,
          metadata: metadataFromProbe(inputProbe),
        };
      } catch {
        // Remux failed (e.g. unusual edit lists) — fall back to a full transcode below.
      }
    }

    const probe = inputProbe ?? (await probeVideoFile(inputPath));
    await runProcess(getFfmpegBin(), buildTranscodeArgs(inputPath, outputPath, probe), timeoutMs);
    const posterSeek = choosePosterSeekSeconds(probe.durationSeconds);
    await runProcess(getFfmpegBin(), buildPosterArgs(outputPath, posterPath, posterSeek), Math.min(timeoutMs, 60_000));

    return {
      success: true,
      method: "ffmpeg-transcode",
      outputBuffer: await readFile(outputPath),
      posterBuffer: (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : null,
      metadata: metadataFromProbe(probe),
    };
  } catch (error) {
    return {
      success: false,
      method: "none",
      outputBuffer: null,
      posterBuffer: null,
      metadata: EMPTY_METADATA,
      error: error instanceof Error ? error.message : "Video processing failed.",
    };
  } finally {
    release();
    await rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

async function fileNonEmpty(p: string): Promise<boolean> {
  try {
    const s = await stat(p);
    return s.size > 0;
  } catch {
    return false;
  }
}

function metadataFromProbe(probe: ProbeResult): ProcessedVideoMetadata {
  return {
    durationSeconds: probe.durationSeconds,
    width: probe.rotation === 90 || probe.rotation === 270 ? probe.height : probe.width,
    height: probe.rotation === 90 || probe.rotation === 270 ? probe.width : probe.height,
    hadHevc: probe.isHevc,
    hadHdr: probe.isHdr,
    hasAudio: probe.hasAudio,
  };
}

/** Metadata for the external-converter path: probe the *input* for hadHevc/hadHdr flags, the *output* for final dimensions/duration. */
async function deriveMetadata(inputPath: string, outputPath: string): Promise<ProcessedVideoMetadata> {
  const [inputProbe, outputProbe] = await Promise.all([
    probeVideoFile(inputPath).catch(() => null),
    probeVideoFile(outputPath).catch(() => null),
  ]);
  return {
    durationSeconds: outputProbe?.durationSeconds ?? inputProbe?.durationSeconds ?? null,
    width: outputProbe?.width ?? null,
    height: outputProbe?.height ?? null,
    hadHevc: inputProbe?.isHevc ?? false,
    hadHdr: inputProbe?.isHdr ?? false,
    hasAudio: outputProbe?.hasAudio ?? inputProbe?.hasAudio ?? false,
  };
}

/** If the external converter didn't produce its own poster, grab one from our ffmpeg as a safety net. */
async function extractPosterFallback(outputPath: string, posterPath: string, durationSeconds: number | null): Promise<Buffer | null> {
  try {
    await runProcess(getFfmpegBin(), buildPosterArgs(outputPath, posterPath, choosePosterSeekSeconds(durationSeconds)), 60_000);
    return (await fileNonEmpty(posterPath)) ? await readFile(posterPath) : null;
  } catch {
    return null;
  }
}
