export const VENDOR_TYPES = [
  { value: "individual", label: "Individual Vendor" },
  { value: "business", label: "Business Vendor" },
  { value: "agency", label: "Event Agency" },
  { value: "venue_owner", label: "Venue Owner" },
  { value: "freelancer", label: "Freelancer" },
  { value: "company", label: "Company" },
] as const;

export const SOCIAL_PLATFORMS = [
  "instagram", "tiktok", "facebook", "snapchat", "trendshub",
  "x", "linkedin", "youtube", "website", "whatsapp",
] as const;

export const DEFAULT_VENDOR_CATEGORIES = [
  { slug: "venues", name: "Venues", icon: "building" },
  { slug: "photographers", name: "Photographers", icon: "camera" },
  { slug: "videographers", name: "Videographers", icon: "video" },
  { slug: "caterers", name: "Caterers", icon: "utensils" },
  { slug: "chefs", name: "Chefs", icon: "chef-hat" },
  { slug: "decorators", name: "Decorators", icon: "sparkles" },
  { slug: "djs", name: "DJs", icon: "music" },
  { slug: "mcs", name: "MCs", icon: "mic" },
  { slug: "security", name: "Security", icon: "shield" },
  { slug: "makeup-artists", name: "Makeup Artists", icon: "palette" },
  { slug: "hair-stylists", name: "Hair Stylists", icon: "scissors" },
  { slug: "fashion-designers", name: "Fashion Designers", icon: "shirt" },
  { slug: "florists", name: "Florists", icon: "flower" },
  { slug: "car-rentals", name: "Car Rentals", icon: "car" },
  { slug: "event-planners", name: "Event Planners", icon: "calendar" },
  { slug: "wedding-coordinators", name: "Wedding Coordinators", icon: "heart" },
  { slug: "funeral-coordinators", name: "Funeral Coordinators", icon: "flower2" },
  { slug: "lighting", name: "Lighting", icon: "lightbulb" },
  { slug: "sound-engineers", name: "Sound Engineers", icon: "volume" },
  { slug: "live-bands", name: "Live Bands", icon: "guitar" },
  { slug: "content-creators", name: "Content Creators", icon: "clapperboard" },
  { slug: "influencers", name: "Influencers", icon: "star" },
  { slug: "drone-operators", name: "Drone Operators", icon: "plane" },
  { slug: "printing-services", name: "Printing Services", icon: "printer" },
  { slug: "cake-designers", name: "Cake Designers", icon: "cake" },
  { slug: "ushers", name: "Ushers", icon: "users" },
  { slug: "hotels", name: "Hotels", icon: "hotel" },
  { slug: "travel-services", name: "Travel Services", icon: "plane" },
] as const;

export const DEFAULT_VENDOR_PLANS = [
  {
    slug: "free",
    name: "Free Vendor",
    priceGhs: 0,
    durationDays: 36500,
    imageLimit: 10,
    videoLimit: 2,
    storageLimitMb: 500,
    categoryLimit: 2,
    portfolioEventLimit: 5,
    verifiedBadge: false,
    featuredSearch: false,
    advancedAnalytics: false,
    priorityLeads: false,
  },
  {
    slug: "verified",
    name: "Verified Vendor",
    priceGhs: 199,
    durationDays: 365,
    imageLimit: 50,
    videoLimit: 20,
    storageLimitMb: 5120,
    categoryLimit: 10,
    portfolioEventLimit: -1,
    verifiedBadge: true,
    featuredSearch: false,
    advancedAnalytics: true,
    priorityLeads: false,
  },
  {
    slug: "premium",
    name: "Premium Vendor",
    priceGhs: 499,
    durationDays: 365,
    imageLimit: 200,
    videoLimit: 50,
    storageLimitMb: 51200,
    categoryLimit: -1,
    portfolioEventLimit: -1,
    verifiedBadge: true,
    featuredSearch: true,
    advancedAnalytics: true,
    priorityLeads: true,
  },
  {
    slug: "enterprise",
    name: "Enterprise Vendor",
    priceGhs: 1499,
    durationDays: 365,
    imageLimit: -1,
    videoLimit: -1,
    storageLimitMb: 102400,
    categoryLimit: -1,
    portfolioEventLimit: -1,
    verifiedBadge: true,
    featuredSearch: true,
    advancedAnalytics: true,
    priorityLeads: true,
  },
] as const;
