/** Public-facing AGI Engine branding — never expose provider names to guests/clients */

export const AGI_ENGINE = {
  name: "AGI Engine",
  tagline: "Powered by AGI Engine",
  intelligence: "Celeventic Intelligence",
  smartDesign: "Smart Design Engine",
  experience: "Experience Engine",
} as const;

export const AGI_COPY = {
  loading: "Your invitation experience is being crafted",
  preparing: "Preparing your premium experience",
  generating: "Generating your premium experience",
  optimizing: "Optimizing your invitation design",
  enhanced: "Enhanced by AGI Engine",
  designed: "Designed with Celeventic Intelligence",
  crafting: "Crafting your invitation experience",
  analyzing: "Analyzing your design inspiration",
  suggest: "Celeventic Smart Design Advisor",
  planner: "Celeventic Event Intelligence",
  contentAssist: "Celeventic Content Intelligence",
} as const;

/** Words that must never appear in user-facing UI */
export const FORBIDDEN_PUBLIC_TERMS = [
  "openai", "chatgpt", "anthropic", "gpt-", "claude", "prompt", "llm", "generated by ai",
] as const;

export function sanitizePublicCopy(text: string): string {
  let out = text;
  for (const term of FORBIDDEN_PUBLIC_TERMS) {
    out = out.replace(new RegExp(term, "gi"), AGI_ENGINE.name);
  }
  return out.replace(/\bAI\b/g, AGI_ENGINE.name);
}
