import type { EventCollaboratorRole } from "@prisma/client";
import { EventPermissionKey } from "./permission-keys";

/** Seed-only defaults — runtime reads from WorkspaceRolePermission table. */
export const DEFAULT_ROLE_PERMISSIONS: Record<EventCollaboratorRole, readonly string[]> = {
  OWNER: Object.values(EventPermissionKey),
  LEAD_ORGANIZER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.EDIT_EVENT,
    EventPermissionKey.MANAGE_COLLABORATORS,
    EventPermissionKey.INVITE_COLLABORATORS,
    EventPermissionKey.EDIT_INVITATIONS,
    EventPermissionKey.MANAGE_GUESTS,
    EventPermissionKey.MESSAGE_GUESTS,
    EventPermissionKey.MANAGE_TICKETS,
    EventPermissionKey.SCAN_QR,
    EventPermissionKey.EDIT_SEATING,
    EventPermissionKey.MANAGE_FINANCES,
    EventPermissionKey.APPROVE_VENDORS,
    EventPermissionKey.UPLOAD_GALLERY,
    EventPermissionKey.MANAGE_MEMORY_VAULT,
    EventPermissionKey.EDIT_TIMELINE,
    EventPermissionKey.MANAGE_COMMUNICATIONS,
    EventPermissionKey.VIEW_ANALYTICS,
    EventPermissionKey.CREATE_TASKS,
    EventPermissionKey.MANAGE_TASKS,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
  ],
  ASSISTANT_ORGANIZER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.EDIT_EVENT,
    EventPermissionKey.INVITE_COLLABORATORS,
    EventPermissionKey.EDIT_INVITATIONS,
    EventPermissionKey.MANAGE_GUESTS,
    EventPermissionKey.MESSAGE_GUESTS,
    EventPermissionKey.EDIT_SEATING,
    EventPermissionKey.UPLOAD_GALLERY,
    EventPermissionKey.EDIT_TIMELINE,
    EventPermissionKey.MANAGE_COMMUNICATIONS,
    EventPermissionKey.CREATE_TASKS,
    EventPermissionKey.MANAGE_TASKS,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
  ],
  DECOR_COORDINATOR: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.EDIT_INVITATIONS,
    EventPermissionKey.UPLOAD_GALLERY,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
    EventPermissionKey.CREATE_TASKS,
  ],
  VENDOR_COORDINATOR: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.APPROVE_VENDORS,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
    EventPermissionKey.CREATE_TASKS,
    EventPermissionKey.MANAGE_TASKS,
  ],
  FINANCE_COORDINATOR: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.MANAGE_FINANCES,
    EventPermissionKey.VIEW_ANALYTICS,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
  ],
  TEAM_MEMBER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.MANAGE_GUESTS,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
    EventPermissionKey.CREATE_TASKS,
  ],
  FAMILY_MEMBER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.MANAGE_GUESTS,
    EventPermissionKey.UPLOAD_GALLERY,
    EventPermissionKey.MANAGE_MEMORY_VAULT,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
  ],
  FINANCE_MANAGER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.MANAGE_FINANCES,
    EventPermissionKey.VIEW_ANALYTICS,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
  ],
  DESIGN_MANAGER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.EDIT_INVITATIONS,
    EventPermissionKey.UPLOAD_GALLERY,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
    EventPermissionKey.CREATE_TASKS,
  ],
  GUEST_MANAGER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.MANAGE_GUESTS,
    EventPermissionKey.MESSAGE_GUESTS,
    EventPermissionKey.EDIT_SEATING,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
  ],
  MARKETING_MANAGER: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.MANAGE_COMMUNICATIONS,
    EventPermissionKey.VIEW_ANALYTICS,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
  ],
  VENDOR: [
    EventPermissionKey.VIEW_EVENT,
    EventPermissionKey.USE_TEAM_CHAT,
    EventPermissionKey.VIEW_ACTIVITY,
    EventPermissionKey.CREATE_TASKS,
  ],
  VIEW_ONLY: [EventPermissionKey.VIEW_EVENT, EventPermissionKey.VIEW_ACTIVITY],
};
